parent: research/conditional/train/configs/baselines/gpt/common.yaml
md5_parent_hash: f10b3c37dd5f7aa8e7282a671a5b37e3
n_gpus: 1
cuda_visible: "5"

params:
  # init
  init_type: truncated_normal
  init_scale: 1.0

  # data
  batch_size: 512
  cutoff: 256

  dmodel: 512
  dff: 2048
  n_blocks: 8
  n_att_heads: 8
  n_steps: 175_000
  final_lr_step: 150_000
  decoding_interval: 0
  ^flash_attention: [true]
  # data_distributed: true
  weight_decay: 0.1
  logging_interval_heavy: 200_000
  tags: ["medium_dense"]
  loss_checkpoint_chungs: 128
  learning_rate: 5e-4
