parent: research/conditional/train/configs/baselines/gpt/common.yaml
md5_parent_hash: f10b3c37dd5f7aa8e7282a671a5b37e3
n_gpus: 2

params:
  n_steps: 525_000
  final_lr_step: 500_000
  dmodel: 256
  dff: 1024
  n_blocks: 4
  n_att_heads: 4
  data_distributed: true
  learning_rate: 0.004
