parent: research/conditional/train/configs/baselines/gpt/common.yaml
md5_parent_hash: f10b3c37dd5f7aa8e7282a671a5b37e3
n_gpus: 2

params:
  n_steps: 525_000
  final_lr_step: 500_000
  dmodel: 512
  dff: 2048
  n_blocks: 4
  n_att_heads: 8
  data_distributed: true
  learning_rate: 4e-3
