parent: configs/baselines/gpt/dense/small.yaml
md5_parent_hash: 9c33561435876b217623fcc532b8ab73
time: "0-20:00:00"
runner: "research.token_reduction.runner"
n_gpus: 1

params:
  # ^cutoff: [256]
  # ^batch_size: [256]
  # ^learning_rate: [1e-5, 2e-5, 5e-5, 1e-4, 2e-4]
  # validation_dataset_path: "/net/tscratch/people/plgcrewtool/cache/validation"
  # train_dataset_path: "/net/tscratch/people/plgcrewtool/cache"

  mixed_precision: false
  # mixed_precision_dtype: bfloat16
  flash_attention: false


  wandb_project: "token_reduction"
  name: "baseline_2048"
  # logger_types: "neptune,wandb"
  grad_clip: 1.0
  tags: ["small","baseline", "lr_tuning"]


  final_lr_step: 100_000
  scheduler: cosine
  lr_warmup_steps: 750
  final_lr_fraction: 0.1
  n_steps: 100_000
  decoding_interval: 0
  logging_interval_heavy: 1000
  init_type: truncated_normal
  init_scale: 0.1
  save_weights_interval: 0
  dataset_type: c4
  weight_decay: 0.1
  eval_interval: 100  


  gradient_accumulation_steps: 1

  learning_rate: 5e-5
  cutoff: 32
  reduced_number_of_tokens: 24
  batch_size: 8
  dmodel: 32
  dff: 128
  n_blocks: 2
  n_att_heads: 2
  use_dummy_dataset: true
  num_workers: 1
  logger_types: "stdout"

