parent: research/conditional/train/configs/baselines/gpt/mot/mini.yaml
md5_parent_hash: 3f34bce59049e43336ce61fe1732bf34
cuda_visible: "4"

time: "00:30:00"

params:
  name: "gradient_accumulation_steps_8"
  gradient_accumulation_steps: 8
  save_weights_interval: 0
  logging_interval_heavy: 1000
  tags: ["cluster_test", "gradient_accumulation_steps"]
  n_steps: 5000