runner: "research.muP_MoE.train.train"

# time: "05:00:00"
time: "00:10:00"

n_gpus: 1
cpus_per_gpu: 16

interactive_debug: false

params:
  name: "muP_MoE_like_gyang_config"
  # tags: ["muP_MoE", "muTransfer", "norm_plot_3"]
  tags: ["muP_MoE", "muTransfer", "10_step_gyangconfig_adamw", "no_fsdp", "ato_remove_after_fix"]

  mup_params:
    ^alpha_in: [1.0]
    ^alpha_out: [1.0]
    # alpha_in: 5.0
    # alpha_out: 0.2
    base_dmodel: 256

  # training
  n_steps: 10
  lr_warmup_steps: 0
  batch_size: 24
  cutoff: 32

  # model
  model_type: gpt
  ^dmodel: [256, 384, 512, 768, 1024, 1536, 2048]
  # ^dmodel: [256, 512, 1024, 2048, 4096]
  # ^dmodel: [256, 512, 1024, 2048]
  n_blocks: 2
  dhead: 64
  attention_mode: 'vanilla'
  attention_normalization: 'dhead'
  use_torch_bmm: true

  ff_mode: vanilla
  dff_ratio: 4

  # learning
  optimizer: adamw # we have adamW
  scheduler: constant
  learning_rate: 1e-2
  final_lr_fraction: 0.1
  grad_clip: 0.25
  weight_decay: 0.0
  init_scale: 1.0
  init_type: truncated_normal
  capacity_factor: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.95

  # other
  dataset_type: c4
  mixed_precision: false
  flash_attention: false
  mixed_precision_dtype: bfloat16
  ^data_seed: [1000, 1001, 1002, 1003, 1004]

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 1
  print_parameter_names: true

  # FSDP
  # fsdp_enabled: true
  # fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock,Attention,FeedForward"
  # activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"
  # fsdp_selective_precision_modules: "AttentionMechanism,RoPE"