defaults:
  - default
  - _self_

trainer:
  train_dataloader:
    datasets:
      /storage_nvme_1/llm-random/datasets/c4/train: 1.0
#      /storage_nvme_4/llm-random/datasets/fineweb/train: 0.2
    dataset_split: train
    num_workers: 4

  eval_dataloader:
    datasets:
      /storage_nvme_1/llm-random/datasets/c4/validation: 1.0
#      /storage_nvme_4/llm-random/datasets/fineweb/train: 0.2
    dataset_split: validation
    num_workers: 4