defaults:
  - default
  - _self_

trainer:
  train_dataloader:
    datasets:
      /storage_nvme_1/llm-random/datasets/c4/train: 0.4
      /storage_nvme_4/llm-random/datasets/fineweb/train: 0.6
    dataset_split: train
    num_workers: 2

  eval_dataloader:
    datasets:
#      /storage_nvme_1/llm-random/datasets/c4/validation: 0.6
      /storage_nvme_4/llm-random/datasets/fineweb/train: 1.0
    dataset_split: validation
    num_workers: 2