parent: research/conditional/train/configs/baselines/gpt/dense/common.yaml
md5_parent_hash: 862d1b7a188a7eddb8b8fa0293682da8

cuda_visible: "0"
params:
  dmodel: 256
  dff: 1024
  n_blocks: 4
  n_att_heads: 4
  
  learning_rate: 0.003
  init_type: "kaiming_uniform"
  init_scale: 1.0
