parent: research/conditional/train/configs/baselines/gpt/dense/common.yaml
md5_parent_hash: 862d1b7a188a7eddb8b8fa0293682da8

cuda_visible: "5"
n_gpus: 1

params:
  tags: ["mamba_tests"]
  dmodel: 256
  dff: 1024
  n_blocks: 4
  n_att_heads: 4
  torch_compile: false
  learning_rate: 1e-4
  init_type: truncated_normal
  init_scale: 0.3
  mixed_precision_dtype: float16
  block_modules: ["feedforward", "mamba"]
  save_weights_interval: 0

  # LOCAL
  dataset_type: wikibook
  use_dummy_dataset: true
  # batch_size: 2
