parent: research/conditional/train/configs/baselines/gpt/dense/common.yaml
md5_parent_hash: 3fee2752870665780890ee027e893e62
interactive_debug: true

params:
  dmodel: 256
  dff: 1024
  n_blocks: 4
  n_att_heads: 4

  save_weights_interval: 25