parent: configs/jm/fsdp_check/apply_fsdp.yaml
md5_parent_hash: 5e71b4c3bcc04b78f9c3b20317513328

params:
  name: "fsdp_check"
  # tags: ["aux_loss_fix", "old_implementation"]
  tags: ["fsdp_check", "fsdp_with_chungs"]

  loss_checkpoint_chungs: 8