time: "0-10:00:00"

params:
  name: "fsdp_check"
  # tags: ["aux_loss_fix", "old_implementation"]
  tags: ["fsdp_check", "medium_lr_grid"]

  # training
  n_steps: 20000
  final_lr_step: 20000
  lr_warmup_steps: 200
  batch_size: 256
  cutoff: 256

  # model
  model_type: gpt
  dmodel: 512
  n_att_heads: 8
  n_blocks: 8
  effective_dff_x: 3  # went from 4 -> 3
  expansion_rate: 8
  granularity: 1
  ff_mode: token_choice
  moe_inner_expert: swi_glu
  use_torch_bmm: true
  softmax_over: experts
  group_granular_moe_by_batch: true
  granular_moe_one_hot_impl: true

  # learning
  scheduler: cosine
  ^learning_rate: ['2e-3, 1e-3']
  final_lr_fraction: 0.1
  grad_clip: 0.5
  weight_decay: 0.01
  init_scale: 0.1
  init_type: truncated_normal
  capacity_factor: 1.0

  # aux losses
  load_balancing_loss_weight: 0.01
  zloss_weight: 0.001

  # other
  dataset_type: c4
  mixed_precision: true
  flash_attention: true
  mixed_precision_dtype: bfloat16

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 5000
  logging_interval_loss: 1000
  save_weights_interval: -1
