parent: configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 763f39978a58f704200275285162594c
n_gpus: 4
time: "0-10:00:00"
skip_copy_code: true
params:
    batch_size_rampup_transition_points: [0.5, 1.0]
    batch_size_rampup_sizes: [128, 256]
    batch_size: 512
    cutoff: 512
    fsdp_enabled: true
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: true
    fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    activation_checkpointing_modules: "TransformerBlock,EmbeddingLayer,PredictionHead"
    # gradient_accumulation_steps: 1
    ff_mode: vanilla
    dataset_type: fineweb-edu
    n_steps: 15_000
    learning_rate: 8e-4
    name: bs_rampup
    tags: [slides_verify]
    decoding_interval: 0
    save_weights_interval: 0
    logging_interval_heavy: 1000
    eval_interval: 1000
    init_type: truncated_normal
    init_scale: 0.1
    scheduler: trapezoidal
    ^lr_trapezoidal_decay_fraction: [0.1, 0.2, 0.4]
    ^lr_warmup_steps: [750, 1500, 3000]