parent: research/conditional/train/configs/baselines/gpt/expert_choice/mini.yaml
md5_parent_hash: 70e08b27a71e93798974d31d3ed38469
interactive_debug: true

params:
  name: "granular_4_mini"
  granularity: 4