parent: research/conditional/train/configs/baselines/gpt/expert_choice/small.yaml
md5_parent_hash: afc795eec27a6181f626b10045190669

params:
  mixed_precision_dtype: "bfloat16"
  name: "granular_4_small"
  granularity: 4