import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# TML-BGW Run Analysis (PK-MLM vs Baseline)\n",
    "\n",
    "This notebook compares **PK-MLM** vs **Baseline** results for runs from **today (the day of running this notebook)** in the W&B project `ideas_cv/tml-bgw`.\n",
    "\n",
    "### Features:\n",
    "1. **Date-filtered Analysis**: Focuses on runs created on the current day.\n",
    "2. **Fast Server-side Querying**: Uses Mongo-style filters to only download runs from today (falling back to the last 7 days if empty), optimizing loading speed.\n",
    "3. **Best-performance Comparison**: Compares the best (minimum) loss and best (maximum) accuracy rather than the last step values by scanning run histories.\n",
    "4. **Token Length Splits**: Automatically processes and aggregates metrics across three token length splits: `<256`, `256-512`, and `>512` tokens.\n",
    "5. **Performance vs Learning Rate**: Plots the best metrics against learning rates for both models side-by-side."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import math\n",
    "from pathlib import Path\n",
    "from datetime import datetime, timedelta, timezone\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import wandb\n",
    "\n",
    "REPO_ROOT = Path.cwd().parent\n",
    "sys.path.insert(0, str(REPO_ROOT / \"src\"))\n",
    "print(\"Imports successful!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Helpers for Querying W&B with Server-Side Filters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_wandb_table(project=\"ideas_cv/tml-bgw\", filters=None, negative_tags=None):\n",
    "    api = wandb.Api()\n",
    "    runs = api.runs(path=project, filters=filters)\n",
    "    \n",
    "    runs_data = []\n",
    "    for run in runs:\n",
    "        run_dict = {\n",
    "            \"sys/id\": run.id,\n",
    "            \"sys/name\": run.name,\n",
    "            \"sys/state\": run.state,\n",
    "            \"sys/tags\": run.tags,\n",
    "            \"sys/created_at\": run.created_at,\n",
    "        }\n",
    "        run_dict.update({f\"config/{k}\": v for k, v in run.config.items()})\n",
    "        run_dict.update({f\"summary/{k}\": v for k, v in run.summary._json_dict.items()})\n",
    "        runs_data.append(run_dict)\n",
    "        \n",
    "    df = pd.DataFrame(runs_data)\n",
    "    if df.empty:\n",
    "        return df\n",
    "        \n",
    "    if negative_tags:\n",
    "        if isinstance(negative_tags, str):\n",
    "            negative_tags = [negative_tags]\n",
    "        for neg_tag in negative_tags:\n",
    "            df = df[\n",
    "                ~df[\"sys/tags\"].apply(\n",
    "                    lambda x: neg_tag in x if isinstance(x, list) else False\n",
    "                )\n",
    "            ]\n",
    "    return df\n",
    "\n",
    "def flatten_config_columns(df, sep=\"/\"):\n",
    "    df = df.copy()\n",
    "    def walk(prefix, value, out):\n",
    "        if isinstance(value, dict):\n",
    "            for k, v in value.items():\n",
    "                walk(f\"{prefix}{sep}{k}\", v, out)\n",
    "        else:\n",
    "            out[prefix] = value\n",
    "            \n",
    "    config_cols = [c for c in df.columns if c.startswith(\"config/\")]\n",
    "    new_rows = []\n",
    "    for _, row in df.iterrows():\n",
    "        flat = {}\n",
    "        for c in config_cols:\n",
    "            walk(c, row[c], flat)\n",
    "        new_rows.append(flat)\n",
    "        \n",
    "    flat_df = pd.DataFrame(new_rows, index=df.index)\n",
    "    df = df.drop(columns=config_cols)\n",
    "    return pd.concat([df, flat_df], axis=1)\n",
    "\n",
    "def solve_config_lr(config_lr):\n",
    "    if pd.isnull(config_lr):\n",
    "        return np.nan\n",
    "    try:\n",
    "        config_lr = float(config_lr)\n",
    "        if config_lr < 1.0:\n",
    "            return config_lr\n",
    "        else:\n",
    "            return 2.0**(-config_lr)\n",
    "    except Exception:\n",
    "        return config_lr"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Query and Filter Runs from the Day of Running"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Define server-side filters to only fetch today's runs\n",
    "today_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)\n",
    "today_start_str = today_start.strftime(\"%Y-%m-%dT%H:%M:%SZ\")\n",
    "\n",
    "filters = {\n",
    "    \"created_at\": {\"$gte\": today_start_str}\n",
    "}\n",
    "\n",
    "print(f\"Fetching runs created since today (UTC: {today_start_str})...\")\n",
    "df_raw = get_wandb_table(project=\"ideas_cv/tml-bgw\", filters=filters)\n",
    "print(f\"Runs created today: {len(df_raw)}\")\n",
    "\n",
    "# 2. Fallback cascade to avoid downloading entire project history if no runs today\n",
    "if len(df_raw) == 0:\n",
    "    print(\"WARNING: No runs found from today. Falling back to runs from the last 7 days.\")\n",
    "    seven_days_ago = today_start - timedelta(days=7)\n",
    "    seven_days_ago_str = seven_days_ago.strftime(\"%Y-%m-%dT%H:%M:%SZ\")\n",
    "    filters_fallback = {\n",
    "        \"created_at\": {\"$gte\": seven_days_ago_str}\n",
    "    }\n",
    "    df_raw = get_wandb_table(project=\"ideas_cv/tml-bgw\", filters=filters_fallback)\n",
    "    print(f\"Runs created in the last 7 days: {len(df_raw)}\")\n",
    "    \n",
    "    if len(df_raw) == 0:\n",
    "        print(\"WARNING: No runs found in the last 7 days. Fetching all runs in the project as a last resort.\")\n",
    "        df_raw = get_wandb_table(project=\"ideas_cv/tml-bgw\")\n",
    "        print(f\"Total runs in project: {len(df_raw)}\")\n",
    "\n",
    "df_filtered = df_raw.copy()\n",
    "\n",
    "# Flatten and clean config columns\n",
    "df_clean = flatten_config_columns(df_filtered)\n",
    "print(f\"Cleaned DataFrame shape: {df_clean.shape}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Extract BEST Metric Values by Scanning Run Histories"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "api = wandb.Api()\n",
    "metrics = [\n",
    "    \"steps/eval/loss_(0-256)\", \"steps/eval/accuracy_(0-256)\",\n",
    "    \"steps/eval/loss_(256-512)\", \"steps/eval/accuracy_(256-512)\",\n",
    "    \"steps/eval/loss_(512-inf)\", \"steps/eval/accuracy_(512-inf)\"\n",
    "]\n",
    "\n",
    "rows = []\n",
    "for idx, row in df_clean.iterrows():\n",
    "    run_id = row[\"sys/id\"]\n",
    "    run_name = row[\"sys/name\"]\n",
    "    created_at = row[\"sys/created_at\"]\n",
    "    \n",
    "    # Determine model type from name\n",
    "    name_lower = str(run_name).lower()\n",
    "    if \"baseline\" in name_lower:\n",
    "        model_type = \"Baseline\"\n",
    "    else:\n",
    "        model_type = \"PK-MLM\"\n",
    "        \n",
    "    # Learning rate extraction with fallbacks\n",
    "    lr = row.get(\"config/trainer/learning_rate\", np.nan)\n",
    "    if pd.isnull(lr):\n",
    "        lr = row.get(\"config/learning_rate\", np.nan)\n",
    "    if pd.isnull(lr):\n",
    "        lr = row.get(\"learning_rate\", np.nan)\n",
    "        \n",
    "    lr = solve_config_lr(lr)\n",
    "    \n",
    "    # Fetch history for split metrics\n",
    "    print(f\"Fetching history for run: {run_name}...\")\n",
    "    try:\n",
    "        run_obj = api.run(f\"ideas_cv/tml-bgw/{run_id}\")\n",
    "        history = run_obj.history(keys=metrics, samples=10000)\n",
    "    except Exception as e:\n",
    "        print(f\"  Failed to fetch history: {e}\")\n",
    "        history = pd.DataFrame()\n",
    "        \n",
    "    best_vals = {\n",
    "        \"run_id\": run_id,\n",
    "        \"name\": run_name,\n",
    "        \"model_type\": model_type,\n",
    "        \"learning_rate\": lr,\n",
    "        \"created_at\": created_at\n",
    "    }\n",
    "    \n",
    "    for m in metrics:\n",
    "        if not history.empty and m in history.columns:\n",
    "            series = history[m].dropna()\n",
    "            if not series.empty:\n",
    "                best_vals[m] = series.min() if \"loss\" in m else series.max()\n",
    "            else:\n",
    "                best_vals[m] = np.nan\n",
    "        else:\n",
    "            # Fallback to summary if history isn't loaded/present\n",
    "            best_vals[m] = row.get(f\"summary/{m}\", np.nan)\n",
    "            \n",
    "    rows.append(best_vals)\n",
    "\n",
    "df_results = pd.DataFrame(rows)\n",
    "df_results"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Plot Comparison of Best Metrics per Learning Rate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, axes = plt.subplots(2, 3, figsize=(18, 12))\n",
    "fig.suptitle(\"Best Loss & Accuracy per Learning Rate by Length Split\", fontsize=22, fontweight=\"bold\", y=0.98)\n",
    "\n",
    "splits = [\n",
    "    (\"0-256\", \"<256 tokens\"),\n",
    "    (\"256-512\", \"256-512 tokens\"),\n",
    "    (\"512-inf\", \">512 tokens\")\n",
    "]\n",
    "\n",
    "colors = {\"Baseline\": \"#e31a1c\", \"PK-MLM\": \"#1f78b4\"}\n",
    "markers = {\"Baseline\": \"s\", \"PK-MLM\": \"o\"}\n",
    "linestyles = {\"Baseline\": \"--\", \"PK-MLM\": \"-\"}\n",
    "\n",
    "for col_idx, (split_key, split_label) in enumerate(splits):\n",
    "    # Row 0: Best Loss\n",
    "    ax_loss = axes[0, col_idx]\n",
    "    loss_col = f\"steps/eval/loss_({split_key})\"\n",
    "    \n",
    "    for m_type in [\"Baseline\", \"PK-MLM\"]:\n",
    "        subset = df_results[(df_results[\"model_type\"] == m_type) & df_results[loss_col].notnull()]\n",
    "        if not subset.empty:\n",
    "            grouped = subset.sort_values(\"learning_rate\").groupby(\"learning_rate\")[loss_col].mean()\n",
    "            ax_loss.plot(\n",
    "                grouped.index,\n",
    "                grouped.values,\n",
    "                marker=markers[m_type],\n",
    "                color=colors[m_type],\n",
    "                linestyle=linestyles[m_type],\n",
    "                label=m_type,\n",
    "                linewidth=2.5,\n",
    "                markersize=9\n",
    "            )\n",
    "    ax_loss.set_title(f\"Best Loss ({split_label})\", fontsize=14, fontweight=\"bold\")\n",
    "    ax_loss.set_xlabel(\"Learning Rate\", fontsize=12)\n",
    "    ax_loss.set_ylabel(\"Min Eval Loss\", fontsize=12)\n",
    "    ax_loss.set_xscale(\"log\")\n",
    "    ax_loss.grid(True, which=\"both\", linestyle=\"--\", alpha=0.5)\n",
    "    ax_loss.legend(fontsize=11)\n",
    "    \n",
    "    # Row 1: Best Accuracy\n",
    "    ax_acc = axes[1, col_idx]\n",
    "    acc_col = f\"steps/eval/accuracy_({split_key})\"\n",
    "    \n",
    "    for m_type in [\"Baseline\", \"PK-MLM\"]:\n",
    "        subset = df_results[(df_results[\"model_type\"] == m_type) & df_results[acc_col].notnull()]\n",
    "        if not subset.empty:\n",
    "            grouped = subset.sort_values(\"learning_rate\").groupby(\"learning_rate\")[acc_col].mean()\n",
    "            ax_acc.plot(\n",
    "                grouped.index,\n",
    "                grouped.values,\n",
    "                marker=markers[m_type],\n",
    "                color=colors[m_type],\n",
    "                linestyle=linestyles[m_type],\n",
    "                label=m_type,\n",
    "                linewidth=2.5,\n",
    "                markersize=9\n",
    "            )\n",
    "    ax_acc.set_title(f\"Best Accuracy ({split_label})\", fontsize=14, fontweight=\"bold\")\n",
    "    ax_acc.set_xlabel(\"Learning Rate\", fontsize=12)\n",
    "    ax_acc.set_ylabel(\"Max Accuracy\", fontsize=12)\n",
    "    ax_acc.set_xscale(\"log\")\n",
    "    ax_acc.grid(True, which=\"both\", linestyle=\"--\", alpha=0.5)\n",
    "    ax_acc.legend(fontsize=11)\n",
    "\n",
    "plt.tight_layout(rect=[0, 0, 1, 0.95])\n",
    "plt.savefig(\"best_loss_acc_vs_lr.png\", dpi=300, bbox_inches=\"tight\")\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "tml-random",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("plots_wandb_bgw.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)

print("Notebook plots_wandb_bgw.ipynb created successfully!")
