#!/bin/bash -l

#SBATCH --array=0-6
#SBATCH --cpus-per-gpu=16
#SBATCH --gres=gpu:4
#SBATCH --job-name=LLMR_300_HP
#SBATCH --mem-per-gpu=125G
#SBATCH --nodes=1
#SBATCH --partition=h100
#SBATCH --time=0-4:00:00

#---------- SCRIPT ----------
PROJECT_HOME_PATH=/storage_nvme_4/projected_compression
VENV_PATH=$PROJECT_HOME_PATH/pc_venv
export HF_HOME=$PROJECT_HOME_PATH/hf_cache

# Check if venv exists
if [ ! -d "$VENV_PATH" ]; then
  echo 'Virtual environment not found. Creating...'
  python3 -m venv "$VENV_PATH"
  pip install --upgrade pip
fi 
source "$VENV_PATH/bin/activate"
pip install --upgrade -r requirements.txt

#-------- SCRIPT END --------


export MASTER_ADDR=$(scontrol show hostname ${SLURM_NODELIST} | head -n 1)
if [ -z "${SLURM_ARRAY_TASK_ID}" ]; then
    export MASTER_PORT=$((40000 + ${SLURM_JOB_ID} % 10000))
else
    export MASTER_PORT=$((30000 + (${SLURM_JOB_ID} % 1250) * 8 + (${SLURM_ARRAY_TASK_ID} % 8)))
fi
srun torchrun --nnodes=${SLURM_NNODES}\
  --nproc-per-node=${SLURM_GPUS_ON_NODE} \
  --rdzv-id=${SLURM_JOBID} \
  --rdzv-backend=c10d \
  --rdzv-endpoint=${MASTER_ADDR}:${MASTER_PORT} \
  main.py \
    --config-path=generated_configs \
    --config-name=config_${SLURM_ARRAY_TASK_ID}.yaml \
    +checkpoint_config.slurm_array_task_id=${SLURM_ARRAY_TASK_ID}