parent: configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 763f39978a58f704200275285162594c
n_gpus: 1
time: "0-01:00:00"
params:
    batch_size_rampup_transition_points: [0.05, 0.1]
    batch_size_rampup_units: tokens
    # batch_size_rampup_transition_points: [152, 457]
    # batch_size_rampup_units: steps
    batch_size_rampup_sizes: [128, 256]
    n_tokens: 0.2  # 0.262144 to match steps configuration
    n_steps: null    # 1266 to match tokens configuration with rampup, 1000 without rampup
    batch_size: 512
    cutoff: 512
    fsdp_enabled: true
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: true
    fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    activation_checkpointing_modules: "TransformerBlock,EmbeddingLayer,PredictionHead"
    gradient_accumulation_steps: 8
    ff_mode: vanilla
    dataset_type: c4
    learning_rate: 5e-4
    name: bs_rampup_refactor
    tags: [v4_scheduler_decay_test]
    scheduler: trapezoidal
    lr_warmup_steps: null
    lr_warmup_tokens: 0.025
    ^lr_trapezoidal_decay_fraction: [0.2, 0.5, 0.8]
    ^lr_trapezoidal_decay_fraction_unit: [tokens, steps]
    decoding_interval: 0
    save_weights_interval: 0
    logging_interval_heavy: 1000
    eval_interval: 1000
    init_type: truncated_normal
    init_scale: 1.0
    n_final_eval_batches: 0
    eval_interval: 0
