parent: configs/baselines/gpt/dense/small.yaml
md5_parent_hash: 9bcdbfe14ff178e8ee90a04000ab9546
# hf_datasets_cache: /raid/NFS_SHARE/home/kamil.ciebiera/datasets/datasets
time: "3:00:00"
n_gpus: 1

params:

  name: "mktest"
  fsdp_enabled: false
  mixed_precision: true
  mixed_precision_dtype: float16
  flash_attention: true
  fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
  activation_checkpointing_modules: "TransformerBlock,EmbeddingLayer,PredictionHead"
  ff_mode: token_choice
  n_experts: 8
  expert_size: 2056
  capacity_factor: 1.0
  load_balancing_loss_weight: 0.01
  tags: ["new", "fsdp", "switch", "multigpu"]

  dataset_type: c4
  # use_dummy_dataset: true
  # dataset_type: wikibook
  n_steps: 100
  learning_rate: 5e-4
  decoding_interval: 0
  # logging_interval_heavy: 10_000
  save_weights_interval: 0
  ^loss_checkpoint_chungs: [8]
  ^gradient_accumulation_steps: [4]
  init_type: truncated_normal
  init_scale: 0.1

  use_dummy_dataset: true
  dmodel: 8
  cutoff: 32
  project_name: "crewtool/mojtestproject"