{'_run_': True, 'common': 
 {'_target_': 'src.definitions.Common', 'dff': 8192, 'dmodel': 2048, 'head_norm': True, 'init_scale': 0.1, 'init_type': 'truncated_normal_fixed', 'model_type': 'gpt', 'sequence_length': 512, 'vocab_size': 128256}, 
 'infrastructure': {'cemetery_experiments_dir': '~/llmrandom_cemetery', 'experiment_prepare_venv_path': '${infrastructure.venv_path}', 'generated_configs_path': 'generated_configs', 
'git': {'remote_name': 'cemetery', 'remote_url': 'git@github.com:llm-random/llm-random-cemetery.git'}, 
'metric_logger': {'_target_': 'src.definitions.MetricLoggerConfig', 'heavy_metrics_calculation_interval': 500, 'name': 'test', 'new_neptune_job': True, 'project_name': 'pmtest/llm-random', 'tags': ['pc', 'nano', 'test_configs'], 'type': 'neptune'}, 
'server': 'entropy', 'slurm': {'cpus-per-task': 16, 'gres': 'gpu:4', 'job-name': 'test', 'mem_per_gpu': '90G', 'nodes': 1, 'ntasks-per-node': 4, 'partition': 'h100', 'time': '0-05:00:00'}, 'venv_path': '/dev/null'}, 
'model': {'_target_': 'src.core.model.LLM', 'embedding': {'_target_': 'src.core.model.TokenEmbedding', 'embedding_dim': '${common.dmodel}', 'init_scale': '${common.init_scale}', 'init_type': '${common.init_type}', 'vocab_size': '${common.vocab_size}'}, 
'head': {'_target_': 'src.core.model.PredictionHead', 'embedding_dim': '${common.dmodel}', 
'init_scale': '${common.init_scale}', 'init_type': '${common.init_type}', 'output_size': '${common.vocab_size}', 'use_layer_norm': '${common.head_norm}'}, 
'tower': {'_target_': 'src.core.model.TransformerTower', 'block_fn': {'_partial_': True, '_target_': 'src.core.model.TransformerBlock', 'attention_fn': {'_partial_': True, '_target_': 'src.core.llama.LlamaAttention', 'causal': True, 'dmodel': '${common.dmodel}', 'init_scale': '${common.init_scale}', 'init_type': '${common.init_type}', 'kv_heads': 8, 'q_heads': 32, 'seq_len': '${common.sequence_length}'}, 
'ff_layer_fn': {'_partial_': True, '_target_': 'src.core.llama.LLamaFeedForward', 'dff': '${common.dff}', 'dmodel': '${common.dmodel}', 'init_scale': '${common.init_scale}', 'init_type': '${common.init_type}'}, 'residual_fn': {'_partial_': True, '_target_': 'src.core.model.PreNormBlock', 'dmodel': '${common.dmodel}', 
'norm_class': {'_partial_': True, '_target_': 'src.core.model.RMSNorm', 'eps': 1e-05}}}, 'n_blocks': 342453134}}, 'overrides': [], 'trainer': {'_partial_': True, '_target_': 'src.core.trainer.Trainer', 'checkpoint': {
'load': {'model_checkpoint_filename': None, 'path': '/home/mstefaniak/checkpoints/llama_1b', 'type': 'huggingface'}, 'save': {'interval': -1, 'model_checkpoint_filename': None, 'path': None, 'training_state_filename': None}}, 
'distributed': {'fsdp': {'mixed_precision': {'dtype': 'bfloat16', 'ignored_classes': ['LayerNorm', 'LlamaAttention']}, 'modules_to_wrap': ['TransformerBlock', 'EmbeddingLayer', 'PredictionHead']}}, 
'eval_dataloader': {'_target_': 'src.core.datasets.get_dataloader', 'dataset_path': '/storage_nvme_1/llm-random/datasets/c4/validation', 'dataset_split': 'validation', 'dataset_type': 'c4', 'num_workers': 12, 'seed': 123, 'sequence_length': '${common.sequence_length}', 
'shuffle': True, 'total_batch_size': '${common.sequence_length}', 'use_new_sampling_method': True, 'world_size_independent': False}, 'eval_interval': 1000, 'gradient_accumulation_steps': 4, 'gradient_clipping': 1.0, 'learning_rate': 5e-05, 
'n_eval_steps': 10, 'n_steps': 2000, 'scheduler': {'_partial_': True, '_target_': 'src.core.schedulers.get_cosine_scheduler_with_warmup', 'final_lr_fraction': 0.1, 'warmup_steps': 500}, 
'train_dataloader': {'_target_': 'src.core.datasets.get_dataloader', 'dataset_path': '/storage_nvme_1/llm-random/datasets/c4/train', 'dataset_split': 'train', 'dataset_type': 'c4', 'num_workers': 12, 'seed': 20001, 'sequence_length': '${common.sequence_length}', 
                     'shuffle': True, 'total_batch_size': '${common.sequence_length}', 'use_new_sampling_method': True, 'world_size_independent': False}, 'weight_decay': 0.1}, 'checkpoint_config': {'slurm_array_task_id': 0}}
