parent: configs/baselines/gpt/dense/medium.yaml
md5_parent_hash: 1706dd43c527be74a6282b0319e9c31e
time: "2-00:00:00"
runner: "research.conditional.train.cc_train"
n_gpus: 1

params:
  name: "okok"
  tags: [""]

  ^cutoff: [256]
  ^batch_size: [256]
  ^learning_rate: [1e-4]
  gradient_accumulation_steps: 1

  n_steps: 10
  final_lr_step: 32_000
  lr_warmup_steps: 320
  final_lr_fraction: 0.1


  # precision / distributed
  mixed_precision: false
  # mixed_precision_dtype: bfloat16
  # flash_attention: true

  # common
  scheduler: cosine
  init_type: truncated_normal
  init_scale: 0.1
  dataset_type: c4
  weight_decay: 0.1
  grad_clip: 1.0
  logger_types: "neptune"

  # intervals
  decoding_interval: 0
  logging_interval_heavy: 1000
  logging_interval_light: 100
  save_weights_interval: 0
  eval_interval: 100

  project_name: "crewtool/mojtestproject"