time: 0-40:00:00
interactive_debug_session: false
runner: research.conditional.train.cc_train

n_gpus: 1

params:
  name: "kanmoe_gran"
  save_weights_interval: -1
  tags: [kan, kanmoe_clean, kanmoe_granularity, lfactor_tune]

  logger_types: "neptune"
  project_name: pmtest/llm-random

  fsdp_enabled: false
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE,ExpertGatingOld,TokenChoiceRouterOld"
  batch_size: 128 # 128
  cutoff: 128
  final_lr_fraction: 0.1
  scheduler: cosine
  final_lr_step: 20000
  n_steps: 20200
  lr_warmup_steps: 200
  grad_clip: 1.0
  weight_decay: 0.01  # mby 0?
  ^learning_rate: [5e-3]
  # learning_rate: 5e-4
  logging_interval_heavy: 200
  logging_interval_loss: 50
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  torch_compile: false
  loss_checkpoint_chungs: 8

  dataset_type: c4

  # MODEL
  model_type: gpt
  activation_type: relu
  dmodel: 256
  effective_dff_x: 4
  expansion_rate: 8
  granularity: 4
  n_blocks: 4
  n_att_heads: 4

  # final_lr_step: 100000
  # n_steps: 101000
  # lr_warmup_steps: 1000
  # logging_interval_heavy: 2000
  # logging_interval_loss: 500

  final_lr_step: 10000
  n_steps: 10100
  lr_warmup_steps: 100
  logging_interval_heavy: 200
  logging_interval_loss: 50

  ff_mode: token_choice
  ^moe_inner_expert: [kan_latent]
  use_torch_bmm: true
  softmax_over: experts

  # init
  ^kan_latent_factor: [1.3, 1.4, 1.5, 1.7]
  kan_parameter_matched: 'true'
  init_scale: 0.1
  init_type: truncated_normal
  init_scale_base: 0.1
  init_scale_spline: 0.1
  init_scale_noise: 0.01

  # debug
  # logger_types: "stdout"
  # use_dummy_dataset: true
  # n_blocks: 1
  # n_att_heads: 1
  # zloss_weight: 0

  # dmodel: 16
  # n_blocks: 1
  # n_att_heads: 2