parent: configs/baselines/gpt/grad_norm/common.yaml
md5_parent_hash: 23ddca6ab48496a38bf21b6f8cb15663
time: 0-12:00:00

cpus_per_gpu: 16
params:
  batch_size: 128
  name: "grad_norm_medium_baseline_reduced_bs"

  # model architecture
  dmodel: 512
  n_blocks: 8
  n_att_heads: 8
  dff: 2048

  # grad norm config
  grad_modif_type:
    - "std_norm"
  grad_modif_params:
    - "c=1.0"
    - "eps=1e-8"
    - "layer_type=v1"
  grad_modif_placement:

  tags:
    - "medium"
    - "grad_norm"
    - "baseline"
    - "reduce_bs"

  # logging etc.
  logging_interval_heavy: 160
  logging_interval_loss: 160

  # hparams
  n_steps: 16_000
  final_lr_step: 14_500
  scheduler: cosine
  lr_warmup_steps: 160
  final_lr_fraction: 0.1
