
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: ea24ed4a5d6558970d3230b69a0c88fa
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm256"]

  ^learning_rate: [0.0005, 0.001, 0.002]

  dmodel: 256
  dff: 256
  n_steps: 8812
  



