
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 426d38a67881ad9b9276b25286a1ce31
time: 0-03:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "medium", "test"]

  dmodel: 512
  dff: 512
  n_steps: 6_800
  residual_mode: pre_norm

  save_weights_path: /local_storage_1/ms_tmp/models/
  # save_weights_path: models_ckpt

  # fsdp_enabled: false

  # fsdp_enabled: true
  # fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
