
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: d233f50504be99b92d74b8ed59810c08
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "small"]

  dmodel: 256
  dff: 256
  n_steps: 1600
  



