
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 7608f909cc9c344e8deacb8dd2113d5d
time: 1-00:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm1024", "doner"]
  
  # ^learning_rate: [0.0000625, 0.000125, 0.00025, 0.0005] #+
  # ^learning_rate: [0.00075, 0.001, 0.002] # 0.0005
  learning_rate: 0.0005

  dmodel: 1024
  dff: 1024
  n_steps: 46_770

  dont_save_final_model: False
  # save_weights_path: /local_storage_1/ms_tmp/models/