
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 6bbc89126d738f215bf51745e143d6bc
time: 2-00:00:00
n_gpus: 8
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm4096", "doner"]

  ^learning_rate: [0.00003125, 0.0000625, 0.000125]
  
  dmodel: 4096
  dff: 4096
  flash_attention: False
  n_steps: 371_403

  dont_save_final_model: False
  # save_weights_path: /local_storage_1/ms_tmp/models/

  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"
