
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 857e8482d095f33083fee68ab10421b4
time: 0-06:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm512", "doner"]

  ^learning_rate: [0.000125, 0.00025, 0.0005, 0.001] #+
  # ^learning_rate: [0.00075, 0.002, 0.004] # 0.001
  # learning_rate: 0.001 # 3.852969 - LLMRANDOM-29157 - /net/pr2/projects/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-01-24_18-16-36/None/1171839/19545.pt
  # ^learning_rate: [0.00075] # double check

  dmodel: 512
  dff: 512
  n_steps: 19_545

  dont_save_final_model: False
  # save_weights_path: /local_storage_1/ms_tmp/models/