
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 099bae218730a43890c603c081288bf9
time: 1-00:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm1024", "doner"]
  
  # ^learning_rate: [0.000125, 0.00025, 0.0005] #+
  # ^learning_rate: [0.00075, 0.001, 0.002] # 0.0005
  learning_rate: 0.0005 # 3.556719 - LLMRANDOM-29154 - /net/pr2/projects/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-01-24_18-15-38/None/1171835/46770.pt

  dmodel: 1024
  dff: 1024
  n_steps: 46_770

  dont_save_final_model: False
  # save_weights_path: /local_storage_1/ms_tmp/models/