
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 099bae218730a43890c603c081288bf9
time: 0-12:00:00
n_gpus: 2
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "compression", "dm1024"]

  dmodel: 1024
  dff: 1024
  projected_dmodel: 2048
  projected_dff: 2048
  n_steps: 46_770 # same as dmodel
  # learning_rate: 0.0005 # same as dmodel
  ^learning_rate: [0.000015625, 0.00003125, 0.0000625, 0.000125, 0.00025, 0.0005, 0.001, 0.002] # ?????????

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  residual_mode: pre_norm_no_bias
  

  # projection_init_type: half
  ^projection_init_type: [half, orthogonal]
  no_projected_head: True
  
  projected_distillation: True
  projected_weights_path: dev
  
  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"






