
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 7608f909cc9c344e8deacb8dd2113d5d
time: 0-16:00:00
n_gpus: 2
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "compression", "dm256"]

  dmodel: 256
  dff: 256
  projected_dmodel: 2048
  projected_dff: 2048
  n_steps: 8812 # same as dmodel
  # learning_rate: 0.0005 # same as dmodel
  ^learning_rate: [0.000125, 0.00025, 0.0005, 0.001] # half+orthogonal - 0.0005 - LLMRANDOM-29377

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  
  # projection_init_type: half
  ^projection_init_type: [half, orthogonal]
  # ^projection_init_type: [half]
 
  projected_distillation: True
  projected_weights_path: /net/pr2/projects/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-01-29_12-07-37/None/1181033/124261.pt
  
  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"






