
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 099bae218730a43890c603c081288bf9
time: 0-02:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "dm256"]

  dmodel: 256
  dff: 256
  projected_dmodel: 512
  projected_dff: 512
  n_steps: 8812 # same as dmodel
  # learning_rate: 0.002 # same as dmodel ?
  ^learning_rate: [0.000125, 0.00025, 0.0005, 0.001, 0.002, 0.004, 0.008, 0.01]

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  residual_mode: pre_norm_no_bias
  

  projection_init_type: half
  ^no_projected_head: True
 
  # ^projection_init_type: [orthagonal]
  # ^no_projected_head: [True, False]
  # ^no_layer_norm: [True, False]

  # ^projection_init_type: [half, orthagonal, null, sum1d]
  # ^no_projected_head: [True, False]


  projected_distillation: True
  projected_weights_path: /net/pr2/projects/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-01-24_18-16-36/None/1171839/19545.pt
  







