
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 099bae218730a43890c603c081288bf9
time: 0-08:00:00
n_gpus: 2
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "compression", "dm256"]

  dmodel: 256
  dff: 256
  projected_dmodel: 2048
  projected_dff: 2048
  n_steps: 8812 # same as dmodel
  # learning_rate: 0.0005 # same as dmodel
  ^learning_rate: [0.00025, 0.0005, 0.001]

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  residual_mode: pre_norm_no_bias
  

  # projection_init_type: half
  ^projection_init_type: [half, orthogonal]
  no_projected_head: True
 
  projected_distillation: True
  projected_weights_path: 
  
  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"






