
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 099bae218730a43890c603c081288bf9
time: 1-00:00:00
n_gpus: 2
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "compression", "dm512_2048"]

  dmodel: 512
  dff: 512
  projected_dmodel: 2048
  projected_dff: 2048
  n_steps: 19_545 # same as dmodel
  # learning_rate: 0.0005 # same as dmodel
  ^learning_rate: [0.000125, 0.00025, 0.0005]

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  residual_mode: pre_norm_no_bias
  
  # projection_init_type: half
  ^projection_init_type: [half, orthogonal]
  # ^projection_init_type: [half]

  projected_distillation: True
  projected_weights_path: /net/pr2/projects/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-01-29_12-07-37/None/1181033/124261.pt
  
  fsdp_use_orig_params: True
  fsdp_enabled: True
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"






