
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 6bbc89126d738f215bf51745e143d6bc
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "compression", "dm512", "test", "dev"]

  dmodel: 512
  dff: 512
  projected_dmodel: 512
  projected_dff: 512
  n_steps: 500 # same as dmodel
  # learning_rate: 0.001 # same as dmodel
  # ^learning_rate: [0.00025, 0.0005, 0.001]
  learning_rate: 0.0001

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  
  projection_init_type: half

  projected_distillation: True
  projected_weights_path: /net/pr2/projects/plgrid/plggllmeffi/plgmstefaniak/llm_random_cemetery/PD_2025-02-10_12-54-15/None/1195464/19545.pt
  # projected_weights_path: /local_storage_1/ms_tmp/models/42951/6800.pt

  # fsdp_use_orig_params: True 
  # fsdp_enabled: True
  # fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
  # fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE"





