
parent: configs/projected_dis/1ff/common.yaml
md5_parent_hash: 3a334a7df4fb5340ca5da7c06952f387
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "1ff", "small", "p_init_grid"]

  dmodel: 256
  dff: 256
  projected_dmodel: 512
  projected_dff: 512
  n_steps: 1600
  learning_rate: 0.0005

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  residual_mode: pre_norm_no_bias
  

  projection_init_type: half
  ^no_projected_head: True
 
  ^projection_init_type: [orthagonal]
  ^no_projected_head: [True, False]
  ^no_layer_norm: [True, False]

  # ^projection_init_type: [half, orthagonal, null, sum1d]
  # ^no_projected_head: [True, False]


  projected_distillation: True
  projected_weights_path: /local_storage_1/ms_tmp/models/42951/6800.pt
  







