hydra:
  searchpath: 
    - file://${oc.env:PWD}/configs/experiments/mtp_merge


training:
  dataloader:
    eval_dataset_path: "/raid/NFS_SHARE/datasets/c4/train/c4_train" #TODO
    training_dataset_path: "/raid/NFS_SHARE/datasets/c4/validation/c4_validation" #TODO
  learning_rate: 5e-4 #TODO

slurm:
  gres: gpu:ampere:1
  time: 3-00:00:00
  # partition: h100 #TODO

venv_path: '$HOME/onefiler/venv/bin/activate' #TODO

checkpoint_config:
  path: "ckpts" #TODO

model:
  common:
    dropped_tokens: 128

defaults:
  - common
  - _self_

server: vpn #TODO
