defaults:
    - configs/clusters: ${__llmrandom_cluster_config:}
    - configs/defaults:
      - checkpoints
      - distributed
      - factories
      - infrastructure
      - metric_logger
      - model
      - training
    - configs/defaults/model_sizes:
      - k8
    - _self_

model:
  common:
    sequence_length: 256

training:
  dataloader:
    total_batch_size: 256
    eval_dataset_path: "/storage_nvme_1/llm-random/datasets/c4/validation"
    training_dataset_path: "/storage_nvme_1/llm-random/datasets/c4/train"

  n_steps: 50001
  learning_rate: 5e-4


  scheduler: 
    config:
      warmup_steps: 500



##### INFRASTRUCTURE #####

slurm:
  job-name: "tr_v_k8"
  gres: gpu:1
  time: 0-06:00:00
  partition: a100
  # ntasks-per-node: 2

checkpoint_config:
    interval: 0
    path: "/storage_ssd_1/crewtool/checkpoints/tr_v_k8"


venv_path: '$HOME/onefiler/venv/bin/activate'

server: entropia

metric_logger:
  name: "tr_v_k8"
  tags: 
    - "vanilla" 
    - "lr=5e-4"