defaults:
    - configs/clusters: ${__llmrandom_cluster_config:}
    - configs/defaults:
      - checkpoints
      - distributed
      - factories
      - infrastructure
      - metric_logger
      - training
    - configs/reduction_defaults:
      - mtp_model
      - mtp_factories
    - configs/defaults/model_sizes:
      - k8
    - _self_

model:
  common:
    sequence_length: 256
  mtp_config:
    _target_: token_reduction.model.MTPConfig
    n_mtp: 2

training:
  dataloader:
    total_batch_size: 256
    eval_dataset_path: "/storage_nvme_1/llm-random/datasets/c4/validation"
    training_dataset_path: "/storage_nvme_1/llm-random/datasets/c4/train"

    # training_dataset_path: "/raid/NFS_SHARE/datasets/c4/train/c4_train"
    # eval_dataset_path: "/raid/NFS_SHARE/datasets/c4/validation/c4_validation"

  n_steps: 50001
  learning_rate: 1e-3


  scheduler: 
    config:
      warmup_steps: 500


##### INFRASTRUCTURE #####

slurm:
  job-name: "tr_mtp_k8"
  time: 0-20:00:00

  # gres: gpu:ampere:1

  gres: gpu:1
  partition: a100

checkpoint_config:
    interval: 0
    # path: "ckpts"
    path: "/storage_nvme_1/crewtool/test"


venv_path: '$HOME/onefiler/venv/bin/activate'

server: entropia

metric_logger:
  name: "tr_mtp_k8"
  tags: 
    - "mtp" 
    - "lr=1e-3"
    - "k8"


