defaults:
  - configs: log
  - lel
  - oo
  - configs/clusters: ${__llmrandom_cluster_config:}

  - _self_

# hydra:
#   launcher:
#       training_dataset_path: data
#       eval_dataset_path: data_eval

training:
    dataloader:
        total_batch_size: 8
        num_workers: 0
    n_steps: 30



infrastructure:
  slurm:
    job-name: "XD"
