parent: research/conditional/train/configs/baselines/rms.yaml
md5_parent_hash: 2895505e7e5650f7c71b692d99163dcf

time: 00:10:00
interactive_debug: true

params:
  project_name: "kamciebiera/testy"

  n_blocks: 1
  ^use_rms_norm: [true]
  ^learning_rate: [1e-3]
  use_dummy_dataset: true
  name: "debug"