parent: configs/baselines/gpt/dense/common.yaml
md5_parent_hash: 1b1451abcd3779c5960c78b2f48aecbc

params:
  dmodel: 768
  dff: 3072
  n_blocks: 12
  n_att_heads: 12
  learning_rate: 1e-4
  init_type: kaiming_uniform
  init_scale: 1.0
  mixed_precision_dtype: bfloat16