runner: "research.blanks.train"
time: 2-00:00:00
n_gpus: 1
interactive_debug: false

# train params
params:
  name: blanx-eval-testing
  learning_rate: 1e-3
  n_steps: 100000
  init_type: kaiming_uniform
  init_scale: 1.0

  # base bass
  mixed_precision: true

  # logging etc.
  use_neptune: true
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 5000
  logging_interval_loss: 1000
  save_weights_path: "model_ckpt"
  save_weights_interval: 25_000

  # shallower bass
  cutoff: 256
  batch_size: 256
  final_lr_step: 100_000
  scheduler: cosine
  lr_warmup_steps: 2500
  final_lr_fraction: 0.1

  grad_clip: 0.5
