# grid args
runner: "research.conditional.train.cc_train"
time: "00:03:00"
n_gpus: 1

# train params
params:
  # model
  batch_size: 2
  cutoff: 256
  name: "mp"
  tags:
    - test_new_datasets
  use_neptune: true
  n_steps: 2500
  dmodel: 128
  dff: 256
  n_blocks: 4
  "^model_type":
    - "bert"
  "^ff_mode":
    - "vanilla"
  ^loss_checkpoint_chungs: [1]
  ^mixed_precision: [true]
  # loss_checkpoint_chungs: 0
  logging_interval_heavy: 1000
  logging_interval_loss: 1000
  # hack_name: batch_size
  num_workers: 0
