arent: research/conditional/train/configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: 55244aca488f24de124c32421737cf2c
name: "expert_choice_base"

params:
  dmodel: 768
  n_blocks: 12
  n_att_heads: 12
