parent: research/conditional/train/configs/baselines/gpt/dense/common.yaml
md5_parent_hash: 862d1b7a188a7eddb8b8fa0293682da8

params:
  name: "expert_choice"

  # technical/common params
  ff_mode: expert_choice
  softmax_over: experts
  group_granular_moe_by_batch: true
  use_full_einsum: true
  granular_moe_one_hot_impl: true

  # params
  expansion_rate: 32
  granularity: 1
  effective_dff_x: 4
  learning_rate: 1e-4

  # init
  init_type: truncated_normal
  init_scale: 0.1
