parent: research/conditional/train/configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: 5828572fff2a7f319748d13d19d223ec
time: 7-00:00:00

params:
  name: "expert_choice_base"
  dmodel: 1024
  n_blocks: 24
  n_att_heads: 16

