parent: research/conditional/train/configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: c7012534fd0496505720405821691611
time: 1-00:00:00

params:
  name: "expert_choice_medium"
  dmodel: 512
  n_blocks: 8
  n_att_heads: 8
