parent: research/conditional/train/configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: cd407955e6a3098e4fdd77f3a7e0fc66
time: 0-05:00:00

params:
  name: "expert_choice_mini"
  dmodel: 256
  n_blocks: 4
  n_att_heads: 4
