parent: research/conditional/train/configs/baselines/gpt/expert_choice/common.yaml
md5_parent_hash: 5828572fff2a7f319748d13d19d223ec
time: 0-05:00:00

params:
  name: "expert_choice_mini"
  dmodel: 256
  n_blocks: 4
  n_att_heads: 4
