parent: research/conditional/train/configs/baselines/gpt/small.yaml
md5_parent_hash: cbdf4e5992f41713488c25c819086e51

params:
  # technical/common params
  ff_mode: expert_choice
  softmax_over: experts
  group_granular_moe_by_batch: true
  use_full_einsum: true
  granular_moe_one_hot_impl: true
  decoding_interval: 0
  learning_rate: 0.0001
  dataset_type: wikibook
  simulate_group_size: 4
  batch_size: 8

  # params of expert choice
  effective_dff: 1024
  total_experts_width: 2048
  n_experts: 32

