parent: research/conditional/train/configs/baselines/expert_choice/mini.yaml
md5_parent_hash: 1b313fc3b6e4080051377be3b808b8f9
name: grouping_test

# time
time: 0-05:00:00
interactive_debug: true

params:
  n_steps: 25_000
  lr_warmup_steps: 2500

  should_evaluate_dynamic_groupsize: true
  n_eval_batches: 10
  eval_interval: 10
  ^simulate_group_size: [8]

  # DEBUG TODO REMOVE
  dataset_type: wikibook  # TODO TYLKO TO JEST TEST REMOVE
  min_eval_group_size: 4
  max_eval_group_size: 16
  batch_size: 16
  cutoff: 16
  dmodel: 64
  n_blocks: 1