parent: configs/jm/cnfg.yaml
md5_parent_hash: aeaff8a5ff59379f93fdba5229f4a73d
time: "01:00:00"

params:
  name: "debug"
  # tags: ["aux_loss_fix", "old_implementation"]
  tags: ["remove"]

  logger_types: "stdout"
  use_dummy_dataset: true
  n_blocks: 4
  dmodel: 16
  n_att_heads: 4

  # training
  n_steps: 100
  final_lr_step: 100
  lr_warmup_steps: 10
  batch_size: 16
  cutoff: 64

  # change
  # print_parameter_names: true

  # model
  model_type: gpt
  dmodel: 16
  n_att_heads: 4
  n_blocks: 4

  ff_mode: vanilla
  dff: 64


  # effective_dff_x: 4  # went from 4 -> 3
  # expansion_rate: 6
  # granularity: 4
  # ff_mode: token_choice
  # moe_inner_expert: relu

  # not working
  # moe_inner_expert: linear