parent: configs/mole/common.yaml
time: 0-05:50:00

# n_gpus: 1 # writer entropy
n_gpus: 2 # athena


# cpus_per_gpu: 20 # writer
# cpus_per_gpu: 32 # entropy
cpus_per_gpu: 16 # athena

md5_parent_hash: 934810b5bf85d2b00bc41bf6e9dc9e5f

params:
  name: "MoLE"
  tags: ["mole", "BCEWithLogitsLoss"]
  ^biased_balancing_loss_weight: [0.125]
  ^load_balancing_loss_weight: [0.015625]
  learning_rate: 0.002

  # num_workers: 16 # writer
  num_workers: 14 # entropy
  # num_workers: 16 # athena
  