time: 0-24:00:00
interactive_debug_session: false
runner: research.conditional.train.cc_train


params:
  name: "principled_moe"
  save_weights_interval: -1


  use_neptune: true
  project_name: pmtest/llm-random


  batch_size: 4
  cutoff: 1024
  final_lr_fraction: 0.1
  scheduler: cosine
  final_lr_step: 25000
  n_steps: 25000
  lr_warmup_steps: 2500
  grad_clip: 0.5
  learning_rate: 1e-4
  logging_interval_heavy: 5000
  logging_interval_loss: 1000
  mixed_precision: true
  mixed_precision_dtype: float16
  torch_compile: false

  dataset_type: c4
  use_dummy_dataset: true

  # MODEL
  model_type: gpt
  activation_type: relu
  dmodel: 768
  n_att_heads: 12
  n_blocks: 1
  cutoff: 256
  effective_dff_x: 4
  expansion_rate: 16
  granularity: 2
  ff_mode: expert_choice
  moe_inner_expert: ff
  use_torch_bmm: true
  # group_granular_moe_by_batch: true

  # init
  init_scale: 0.1
  init_type: truncated_normal

  # ^use_principled_moe: [true]
  ^use_principled_moe: [false]
  
  
  softmax_over: experts
  group_granular_moe_by_batch: true
  use_torch_bmm: true
  torch_compile: false
  granular_moe_one_hot_impl: true
  layer_norm_in_expert_choice: true

