runner: "research.attention_moe.train.train"
time: 0-24:00:00
n_gpus: 4
interactive_debug: false
backends_module: research.attention_moe.backends


# train params
params:
  name: "momqa_extra_mqa"

  # base bass
  mixed_precision: true
  flash_attention: true

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 500
  logging_interval_light: 100
  logging_interval_loss: 1000
  save_weights_path: "model_ckpt"
  save_weights_interval: -1
  tags: ["momqa_the_works"]


  cutoff: 512
  batch_size: 256
  n_steps: 30_000
  final_lr_step: 30_000
  scheduler: cosine
  lr_warmup_steps: 150
  final_lr_fraction: 0.1
  gradient_accumulation_steps: 1

  grad_clip: 1.0
  model_type: gpt
  dataset_type: c4
  # ^capacity_factor: [1.0, 1.25]
  # ^capacity_factor: [1.0]
  weight_decay: 0.01
  topk: 1
  
  # model
  # ^attention_mode: ["vanilla", "gqa"]
  # ^attention_mode: ["gqa", "momqa"]
  ^attention_mode: ["gqa"]
  ^dmodel: [768]
  dff: 3072
  n_blocks: 12
  n_att_heads: 16
  ^n_kv_heads: [1, 2, 4]
  ^learning_rate: [1e-3]
  data_seed: 42
  init_type: truncated_normal
  init_scale: 0.1
  mixed_precision_dtype: bfloat16
  # ^load_balancing_loss_weight: [0.01, 0.0]
  # momqa_use_dropped_tokens_head: true
  ^momqa_use_extra_mqa: [true]
  use_qk_norm: true
  use_rope: true

  # fsdp
  fsdp_enabled: true
  fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
  fsdp_selective_precision_modules: "AttentionMechanism,RoPE"
  torch_compile: false
  # 