runner: "research.attention_moe.train.train"
time: 0-12:00:00
n_gpus: 2
interactive_debug: false

# train params
params:
  name: "load_balancing_momqa"

  # base bass
  mixed_precision: true
  flash_attention: true

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 500
  logging_interval_light: 100
  logging_interval_loss: 1000
  save_weights_path: "model_ckpt"
  save_weights_interval: -1
  tags: ["logging_momqa"]


  cutoff: 512
  batch_size: 256
  n_steps: 15_000
  final_lr_step: 15_000
  scheduler: cosine
  lr_warmup_steps: 150
  final_lr_fraction: 0.1

  grad_clip: 1.0
  model_type: gpt
  dataset_type: c4
  
  # model
  ^attention_mode: ["momqa"]
  ^dmodel: [768]
  dff: 3072
  n_blocks: 12
  n_att_heads: 16
  ^learning_rate: [3e-3]
  data_seed: 42
  init_type: kaiming_uniform
  init_scale: 1.0
  mixed_precision_dtype: bfloat16
  ^load_balancing_loss_weight: [0.01]

  # fsdp
  fsdp_enabled: true
  fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
  fsdp_selective_precision_modules: "AttentionMechanism,RoPE"
  torch_compile: false
