defaults:
  - ../../_misc@_here_: default
  - ../../_cluster@_here_: helios
  - ../../_model/llama@_here_: projected_mem_eff_1B
  - ../../_dataset@_here_: fineweb
  - ../../_trainer@_here_: llama
  - _self_

common:
  batch_size: 512
  sequence_length: 1024

  # dmodel: 1344 # 50
  # dff: 5376
  dmodel: 960  # 30
  dff: 3840
  # dmodel: 448 # 10
  # dff: 1728


projected_compression:
  modules_to_shard:
    - src.projected_compression.mem_eff.CompressibleBlock
    - ${model.source_model.embedding._target_}
    - ${model.source_model.encoder.block_fn._target_}
    - ${model.source_model.head._target_}

  source_model_path: "/net/scratch/hscra/plgrid/plgcrewtool/nano_weights/llama_3_2_1B_nano.pt"
  path_to_importances: "/net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/llama_1_fw_importances/minitron_dimensions_importances.pt"

  init_norms_with_ones: false

  separate_block_optimizers: true

  adjust_grad_norm: true

trainer:
  _target_: src.projected_compression.trainer.PCTrainer
  gradient_accumulation_steps: 16
  n_steps: 2048
  
  learning_rate: 13

  distributed:
    fsdp2: null

  checkpoint:
    save:
      type: nano
      path: "/net/scratch/hscra/plgrid/plgcrewtool/mem_eff_1b/wazna_proba/10p_6" # CHANGE

  scheduler:
    warmup_steps: 40

model:
  cast_bfloat16: false # whether to cast bfloat16 when calculating compressed matrix

infrastructure:
  metric_logger:
    name: Llame_PC
    tags:
      - sanity_check
  slurm:
    time: "0-08:00:00"
  cemetery_experiments_dir: "/net/scratch/hscra/plgrid/plgcrewtool/pc_cemetery"
