defaults:
  - ../../_misc@_here_: default
  - ../../_cluster@_here_: helios
  - ../../_model/llama@_here_: projected_mem_eff_8B
  - ../../_dataset@_here_: fineweb
  - ../../_trainer@_here_: llama
  - _self_

common:
  batch_size: 512
  sequence_length: 2048

  # dmodel: 3072 # 50
  # dff: 9216
  # dmodel: 2160 # 30
  # dff: 6480
  dmodel: 1056 # 10
  dff: 3168


projected_compression:
  modules_to_shard:
    - src.projected_compression.mem_eff.CompressibleBlock
    - ${model.source_model.embedding._target_}
    - ${model.source_model.encoder.block_fn._target_}
    - ${model.source_model.head._target_}

  source_model_path: "/net/scratch/hscra/plgrid/plgcrewtool/nano_weights/llama_3_1_8B_nano.pt"
  path_to_importances: "/net/scratch/hscra/plgrid/plgcrewtool/importances/8b/minitron_dimensions_importances.pt"
  # path_to_importances: "/net/scratch/hscra/plgrid/plgcrewtool/importances/8b/magnitude_dimensions_importances.pt"
  # path_to_importances: "/net/scratch/hscra/plgrid/plgcrewtool/importances/8b/random_dimensions_importances.pt" 

  init_norms_with_ones: false

  separate_block_optimizers: true

  adjust_grad_norm: true

trainer:
  _target_: src.projected_compression.trainer.PCTrainer
  gradient_accumulation_steps: 32
  n_steps: 4096 
  # 2048
  
  ^learning_rate: 
    # - 13
    - 14

  distributed:
    fsdp2: null

  checkpoint:
    save:
      type: nano
      path: "/net/scratch/hscra/plgrid/plgcrewtool/mem_eff_8b__2node_10p/4k" # CHANGE
      interval: 4095

  # train_dataloader:
  #   dataset:
  #     seed: 124


model:
  cast_bfloat16: false # whether to cast bfloat16 when calculating compressed matrix

infrastructure:
  metric_logger:
    name: Llame_PC
    tags:
      - nano
      - pc
      - mem_eff
      - 8B
      - 10p
      - minitron_importances
      # - test
      # - magnitude_importances
      # - random_importances

  slurm:
    # time: "0-01:00:00"
    nodes: 2