runner: "research.conditional.train.cc_train"
time: 0-12:00:00
n_gpus: 2
interactive_debug: false
backends_module: research.dummy_backends_project.infrastructure

# train params
params:
  name: "test_backends"

  # base bass
  mixed_precision: true
  flash_attention: true
  dataset_type: c4

