runner: "research.conditional.train.cc_train"
time: 0-12:00:00
n_gpus: 1
interactive_debug: false

# train params
params:
  name: "debug_diff"
  norm_class: learn_norm
  mean_loss_weight: 0.0
  std_loss_weight: 0.0

  # base bass
  mixed_precision: true
  flash_attention: true

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 1000
  logging_interval_light: 500
  logging_interval_loss: 1000
  save_weights_path: "model_ckpt"
  save_weights_interval: -1
  tags: ["debug_learnnorm"]


  cutoff: 1024
  batch_size: 64
  n_steps: 30_000
  final_lr_step: 30_000
  scheduler: cosine
  lr_warmup_steps: 300
  final_lr_fraction: 0.1
  gradient_accumulation_steps: 1

  grad_clip: 1.0
  model_type: gpt
  dataset_type: c4
  # capacity_factor: 1.25
  weight_decay: 0.01
  # topk: 1
  
  # model
  ^dmodel: [768]
  dff: 3072
  n_blocks: 12
  n_att_heads: 12
  ^learning_rate: [1e-3]
  data_seed: 42
  init_type: truncated_normal
  init_scale: 0.1
  mixed_precision_dtype: bfloat16


  # fsdp
  fsdp_enabled: true
  fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
  fsdp_selective_precision_modules: "AttentionMechanism,RoPE"
  torch_compile: false
  