parent: research/conditional/train/configs/baselines/gpt/mini.yaml
md5_parent_hash: 019212718f2ace8645ddca8f28f6eaee
time: 00:10:00
n_gpus: 2
params:
  data_distributed: true
  learning_rate: 0.003
  mixed_precision: true
  loss_checkpoint_chungs: 8
  name: "Chungus_multigpu_test"
  init_type: "truncated_normal"
  init_scale: 0.1
  

  