parent: research/conditional/train/configs/baselines/gpt/base.yaml
md5_parent_hash: 1cc2f52ca625d4d24f327c4874413d0c
time: 00:10:00
n_gpus: 1
cuda_visible: "6"
params:
  learning_rate: 0.0003
  loss_checkpoint_chungs: 8
  name: "Chungus_max_vram_new"
  hack_name: "batch_size"
  init_type: "truncated_normal"
  init_scale: 0.1
  mixed_precision: true
  