parent: research/conditional/train/configs/baselines/gpt/expert_choice/medium.yaml
md5_parent_hash: 27fc0993c16973ac3b512a9983fefce6
singularity_image: /common/llm-random/images/sparsity_2023.12.14_16.44.42.sif
cuda_visible: "0"
interactive_debug: true
params:
    #tuning
    learning_rate: 1e-4
    # load_balancing_loss_weight: 0.0 # wyjebać
    # capacity_factor: 1.25 # literatoora

    #name
    name: mamba_moe
    tags: ["mamba", "moe", "expert_choice"]

    #mot

    # N_experts: 32 every expert size of normal DFF in vanilla


    #data
    batch_size: 256
    # batch_size: 32
    # batch_size: 2
    dataset_type: c4

    #eval and logging
    log_gradients_and_weights: false
    decoding_interval: 0
    # logging_interval_heavy: 1000
    logging_interval_heavy: -1
    save_weights_interval: 0



    #fsdp
    fsdp_enabled: true
    fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
    activation_checkpointing_modules: "EmbeddingLayer,PredictionHead,TransformerBlock"
    fsdp_selective_precision_modules: ["ExpertGating"]
    grad_clip: 0.5

    #throughput
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: false
    # gradient_accumulation_steps: 1 #!!!!!!!!!!!! THIS IS NONTRIVIAL
    # loss_checkpoint_chungs: 8 # szymon ma 8
    init_type: truncated_normal
    init_scale: 0.1
    n_steps: 100_000

    #mamba

    block_modules: ["mamba", "feedforward"]
    no_positional_embedding: true
    
