parent: research/conditional/train/configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 17e23fa8efdf44ed2a84b8e15941039c
interactive_debug: false
# cuda_visible: "0"
n_gpus: 1
# n_gpus: 0

time: "00:10:00"
params:
    # fsdp_enabled: true
    mixed_precision: true
    mixed_precision_dtype: bfloat16
    flash_attention: true
    # fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
    # activation_checkpointing_modules: "TransformerBlock,EmbeddingLayer,PredictionHead"
    ^loss_checkpoint_chungs: [4]


    ff_mode: vanilla

    dataset_type: c4
    n_steps: 600
    learning_rate: 5e-4
    batch_size: 128
    name: test_chungus_baseline
    tags: ["test_chungus_baseline", "new_not_retain", "base"]
    decoding_interval: 0
    save_weights_interval: 0
    # logging_interval_heavy: 1000
    # eval_interval: 1000
    init_type: truncated_normal
    init_scale: 1.0
    profiler_enabled: true
    profiler_trace_path: "profiler_trace_base"
    profiler_schedule_wait: 50
    profiler_schedule_warmup: 2
    profiler_schedule_active: 1
    profiler_schedule_repeat: 1
    profiler_schedule_skip_first: 500