# @package _global_
defaults:
  - /_cluster@_here_:                entropy
  - /_model/context_scaling@_here_:  template
  - /_trainer@_here_:                context_scaling
  - /_dataset@_here_:                fineweb
  - /_checkpoints/context_scaling@_here_: shared_entropy
  - /_infrastructure@_here_:         default
  - /_downstream_eval@_here_:        joint

  - /_feedforward:                   dense
  - /_attention:                     mha
  - /_parameterization:              simpleP_k12
  - _self_

common:
  n_blocks: 12
  # ^batch_size: [8, 16, 32, 64]
  batch_size: 32
  sequence_length: 1024

trainer:
  n_steps: 2_001
  # ^learning_rate: [4, 6, 8, 10, 11, 12]
  learning_rate: 10
  eval_interval: 100
  n_eval_steps: 5
  downstream_eval_interval: -1
  fixed_eval: true
  scheduler:
    warmup_steps: 1000
  eval_dataloader:
    total_batch_size: 128

infrastructure:
  metric_logger:
    heavy_metrics_calculation_interval: 250 # change on longer runs
    name: main_grid_1
    tags:
      - nano
      - main_grid_1_test
      - dense
      - mha
      - simpleP_k12
      - k12
      - bs${common.batch_size}
      - lr${trainer.learning_rate}
      - ${now:%Y-%m-%d}

  slurm:
    time: "0-04:00:00"
    gres: gpu:4
    job-name: ${infrastructure.metric_logger.name}
