parent: research/conditional/train/configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 17e23fa8efdf44ed2a84b8e15941039c

params:
  learning_rate: 1e-4

  # init
  init_type: truncated_normal
  init_scale: 0.1
