parent: research/conditional/train/configs/baselines/gpt/dense/medium.yaml
md5_parent_hash: 7a0330388646a9bfbcbee67008f9538a

params:
  learning_rate: 1e-4

  # init
  init_type: truncated_normal
  init_scale: 0.1
