parent: research/conditional/train/configs/baselines/gpt/dense/mini.yaml
md5_parent_hash: e1b1c5b4c4b77c4b3bf28fd171ab1c69

params:
  learning_rate: 1e-4

  # init
  init_type: truncated_normal
  init_scale: 0.1

  save_weights_interval: 25