parent: research/conditional/train/configs/baselines/gpt/dense/small.yaml
md5_parent_hash: 652f7951e4c6fb8398fdeadf451067cb

params:
  learning_rate: 1e-4

  # init
  init_type: truncated_normal
  init_scale: 0.1