
parent: configs/projected_dis/common.yaml
md5_parent_hash: 6c71c5ac18a5554a54adacab603e00eb
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "small", "lr_grid"]

  dmodel: 256
  dff: 1024
  n_steps: 3_200
  ^learning_rate: [0.00125, 0.00125, 0.001, 0.0075, 0.0005]

  residual_mode: pre_norm_no_bias