
parent: configs/projected_dis/common.yaml
md5_parent_hash: 49ce21414901578ae2d5e0bbbe097c10
time: 0-02:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "small", "long"]

  dmodel: 256
  dff: 1024
  n_steps: 12_800