
parent: configs/projected_dis/common.yaml
md5_parent_hash: cec3a546f1c5414199beabfa867b592d
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "small", "lr_grid"]

  dmodel: 256
  dff: 1024
  n_steps: 3_200
  # ^learning_rate: [0.0015, 0.00125, 0.001, 0.0075, 0.0005]
  ^learning_rate: [0.0015]

  residual_mode: pre_norm_no_bias