
parent: configs/projected_dis/common.yaml
md5_parent_hash: 426d38a67881ad9b9276b25286a1ce31
time: 0-01:00:00
n_gpus: 2
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "small", "long"]

  # ^dmodel: [256, 256]
  dmodel: 256
  dff: 1024
  # n_steps: 3_200
  n_steps: 12_800
  # lr_warmup_percent: 0.0025 

  # ^fsdp_enabled: [true, false]

  # fsdp_enabled: false

  fsdp_enabled: true
  fsdp_modules_to_wrap: "EmbeddingLayer,PredictionHead,TransformerBlock"
