
parent: configs/projected_dis/common.yaml
md5_parent_hash: 6c71c5ac18a5554a54adacab603e00eb
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16

params:
  name: "PD"
  tags: ["projected_dis", "small", "all_distillation", "lr_grid"]

  dmodel: 256
  dff: 1024
  projected_dmodel: 512
  projected_dff: 2048
  # n_steps: 12_800
  n_steps: 3_200
  # n_steps: 320
  ^learning_rate: [0.0003, 0.0004, 0.0005, 0.0006, 0.0007]

  attention_mode: projected_vanilla
  ff_mode: projected_vanilla
  # residual_mode: pre_norm
  residual_mode: pre_norm_no_bias
  # ^residual_mode: [pre_norm_no_bias, pre_norm]
  no_layer_norm: True
  
  projection_init_type: null
  # projection_init_type: random
  # projection_init_type: sum1d
  # projection_init_type: half
  # projection_init_type: orthagonal
  # projection_init_type: col1
  # projection_init_type: asd
  # ^projection_init_type: [orthagonal, col1]
  # ^projection_init_type: [null, random, sum1d, half, orthagonal, col1]

  projected_distillation: True
  projected_weights_path: /local_storage_1/ms_tmp/models/41986/12800.pt # no_bias_layer_norm and no_ff_bias
  
  # save_weights_path: /local_storage_1/ms_tmp/models/
  # ^dont_save_final_model: [True, False]






