_run_: true

cluster_switch:
  eval_path_c4: /lustre/pd01/plgrid/plgllmefficont2/datasets/c4/validation
  eval_path_fineweb: /lustre/pd01/plgrid/plgllmefficont2/crewtool/proba2/fineweb-edu/train/train
  train_path_c4: /lustre/pd01/plgrid/plgllmefficont2/datasets/c4/train
  train_path_fineweb: /lustre/pd01/plgrid/plgllmefficont2/crewtool/proba2/fineweb-edu/train/train

common:
  base_dff: 14336
  base_dmodel: 4096
  batch_size: 512
  dff: 9216
  dhead: 128
  dmodel: 3072
  kv_heads: 8
  n_blocks: 32
  q_heads: 32
  sequence_length: 2048

common_distillation:
  datt: 4096
  dff: 14336
  dmodel: 4096
  kv_heads: 8
  n_blocks: 32
  q_heads: 32
  vocab_size: 128256

distillation:
  load:
    path: meta-llama/Llama-3.1-8B
    type: pc_memeff_base
  teacher_model:
    _target_: src.projected_compression.model.LLM
    embedding:
      _target_: src.projected_compression.model.TransformerEmbedding
      dmodel: ${common_distillation.dmodel}
      init_fn:
        _partial_: true
        _target_: src.projected_compression.model.trunc_normal_
      vocab_size: ${common_distillation.vocab_size}
    encoder:
      _target_: src.projected_compression.model.TransformerEncoder
      block_fn:
        _partial_: true
        _target_: src.projected_compression.model.TransformerBlock
        attention_fn:
          _partial_: true
          _target_: src.projected_compression.model.RoPEAttention
          dmodel: ${common_distillation.dmodel}
          k_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.dmodel}
            out_features: ${eval:'(${common_distillation.datt} // ${distillation.teacher_model.encoder.block_fn.attention_fn.q_heads})
              * ${distillation.teacher_model.encoder.block_fn.attention_fn.kv_heads}'}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          kv_heads: ${common_distillation.kv_heads}
          o_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.datt}
            out_features: ${common_distillation.dmodel}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          q_heads: ${common_distillation.q_heads}
          q_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.dmodel}
            out_features: ${common_distillation.datt}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          rope_base: 500000
          rope_scale_freqs: true
          seq_len: ${common.sequence_length}
          v_proj_fn: ${distillation.teacher_model.encoder.block_fn.attention_fn.k_proj_fn}
        ff_layer_fn:
          _partial_: true
          _target_: src.projected_compression.model.ProjectedLlamaFeedForward
          ff_post_act_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.dff}
            out_features: ${common_distillation.dmodel}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          ff_pre_act_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.dmodel}
            out_features: ${common_distillation.dff}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          gate_fn: ${distillation.teacher_model.encoder.block_fn.ff_layer_fn.ff_pre_act_fn}
        norm_fn:
          _partial_: true
          _target_: src.core.model.RMSNorm
          eps: 1.0e-05
          normalized_shape: ${common_distillation.dmodel}
      n_blocks: ${common_distillation.n_blocks}
    head:
      _target_: src.projected_compression.model.TransformerHead
      linear_fn:
        _partial_: true
        _target_: src.projected_compression.model.Linear
        in_features: ${common_distillation.dmodel}
        out_features: ${common_distillation.vocab_size}
        partial_init_fn:
          _partial_: true
          _target_: src.projected_compression.model.llm_random_weight_init
          scale: 1
      norm_fn:
        _partial_: true
        _target_: src.core.model.RMSNorm
        eps: 1.0e-05
        normalized_shape: ${common_distillation.dmodel}

evaluator: null

infrastructure:
  cemetery_experiments_dir: ~/llmrandom_cemetery
  generated_configs_path: generated_configs
  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git
  max_concurrent_jobs: null
  metric_logger:
    heavy_metrics_calculation_interval: 100
    name: Llame_PC
    new_wandb_job: true
    project_name: llm-random-test
    tags:
    - nano
    - pc
    - llama_8
    - projected_compression
    - mem_eff
    - distillation
    - 50p
    type: wandb
    wandb_entity: ideas_cv
  script:
  - ${export_env_variables_placeholders:}
  - export HF_HOME="/lustre/pd01/plgrid/plgllmefficont2/crewtool/hf"
  - export HYDRA_FULL_ERROR=1
  - export PIXI_HOME=/lustre/pd01/plgrid/plgllmefficont3/nano/plgj321m/pixi
  - export PATH="$HOME/.pixi/bin:$PATH"
  - export XDG_DATA_HOME="$PROJECT_HOME_PATH/data"
  - export XDG_CACHE_HOME="$PROJECT_HOME_PATH/cache"
  - export XDG_STATE_HOME="$PROJECT_HOME_PATH/state"
  - cd "$PIXI_HOME"
  - eval "$(pixi shell-hook)"
  - cd -
  server: lem
  slurm:
    account: plgllmefficont3
    cpus_per_gpu: 16
    gres: gpu:hopper:4
    job-name: ${infrastructure.metric_logger.name}
    mem_per_gpu: 220G
    nodes: 2
    partition: plgrid-lem-gpu-h100
    time: 2-00:00:00

init_model_opt_sched_fn:
  _partial_: true
  _target_: src.projected_compression.initialization.init_pc_attributes
  source_model_for_distillation: true

model:
  _target_: src.projected_compression.mem_eff.MemoryEfficientProjectedCompression
  cast_bfloat16: false
  source_model:
    _target_: src.projected_compression.model.LLM
    embedding:
      _target_: src.projected_compression.model.Embedding
      embedding_dim: ${common.base_dmodel}
      num_embeddings: 128256
    encoder:
      _target_: src.projected_compression.model.TransformerEncoder
      block_fn:
        _partial_: true
        _target_: src.projected_compression.model.TransformerBlock
        attention_fn:
          _partial_: true
          _target_: src.projected_compression.model.RoPEAttention
          dmodel: ${common.base_dmodel}
          k_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common.base_dmodel}
            out_features: ${eval:'${common.dhead} * ${model.source_model.encoder.block_fn.attention_fn.kv_heads}'}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          kv_heads: ${common.kv_heads}
          o_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${eval:'${common.dhead} * ${model.source_model.encoder.block_fn.attention_fn.q_heads}'}
            out_features: ${common.base_dmodel}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          q_heads: ${common.q_heads}
          q_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common.base_dmodel}
            out_features: ${eval:'${common.dhead} * ${model.source_model.encoder.block_fn.attention_fn.q_heads}'}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          rope_base: 500000
          rope_scale_freqs: true
          seq_len: ${common.sequence_length}
          v_proj_fn: ${model.source_model.encoder.block_fn.attention_fn.k_proj_fn}
        ff_layer_fn:
          _partial_: true
          _target_: src.projected_compression.model.ProjectedLlamaFeedForward
          ff_post_act_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common.base_dff}
            out_features: ${common.base_dmodel}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          ff_pre_act_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common.base_dmodel}
            out_features: ${common.base_dff}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          gate_fn: ${model.source_model.encoder.block_fn.ff_layer_fn.ff_pre_act_fn}
        norm_fn:
          _partial_: true
          _target_: src.core.model.RMSNorm
          eps: 1.0e-05
          normalized_shape: ${common.base_dmodel}
      n_blocks: ${common.n_blocks}
    head:
      _target_: src.projected_compression.model.TransformerHead
      linear_fn:
        _partial_: true
        _target_: src.projected_compression.model.Linear
        in_features: ${common.base_dmodel}
        out_features: ${model.source_model.embedding.num_embeddings}
        partial_init_fn:
          _partial_: true
          _target_: src.projected_compression.model.llm_random_weight_init
          scale: 1
      norm_fn:
        _partial_: true
        _target_: src.core.model.RMSNorm
        eps: 1.0e-05
        normalized_shape: ${common.base_dmodel}
  target_model:
    _target_: src.projected_compression.model.LLM
    embedding:
      _target_: src.projected_compression.model.Embedding
      embedding_dim: ${common.dmodel}
      num_embeddings: 128256
    encoder:
      _target_: src.projected_compression.model.TransformerEncoder
      block_fn:
        _partial_: true
        _target_: src.projected_compression.model.TransformerBlock
        attention_fn:
          _partial_: true
          _target_: src.projected_compression.model.RoPEAttention
          dmodel: ${common.dmodel}
          k_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common.dmodel}
            out_features: ${eval:'${common.dhead} * ${model.target_model.encoder.block_fn.attention_fn.kv_heads}'}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          kv_heads: ${common.kv_heads}
          o_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${eval:'${common.dhead} * ${model.target_model.encoder.block_fn.attention_fn.q_heads}'}
            out_features: ${common.dmodel}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          q_heads: ${common.q_heads}
          q_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common.dmodel}
            out_features: ${eval:'${common.dhead} * ${model.target_model.encoder.block_fn.attention_fn.q_heads}'}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          rope_base: 500000
          rope_scale_freqs: true
          seq_len: ${common.sequence_length}
          v_proj_fn: ${model.target_model.encoder.block_fn.attention_fn.k_proj_fn}
        ff_layer_fn:
          _partial_: true
          _target_: src.projected_compression.model.ProjectedLlamaFeedForward
          ff_post_act_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common.dff}
            out_features: ${common.dmodel}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          ff_pre_act_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common.dmodel}
            out_features: ${common.dff}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          gate_fn: ${model.target_model.encoder.block_fn.ff_layer_fn.ff_pre_act_fn}
        norm_fn:
          _partial_: true
          _target_: src.core.model.RMSNorm
          eps: 1.0e-05
          normalized_shape: ${common.dmodel}
      n_blocks: ${common.n_blocks}
    head:
      _target_: src.projected_compression.model.TransformerHead
      linear_fn:
        _partial_: true
        _target_: src.projected_compression.model.Linear
        in_features: ${common.dmodel}
        out_features: ${model.target_model.embedding.num_embeddings}
        partial_init_fn:
          _partial_: true
          _target_: src.projected_compression.model.llm_random_weight_init
          scale: 1
      norm_fn:
        _partial_: true
        _target_: src.core.model.RMSNorm
        eps: 1.0e-05
        normalized_shape: ${common.dmodel}

overrides:
- trainer.n_steps=4096

projected_compression:
  adjust_grad_norm: false
  init_norms_with_ones: false
  modules_to_shard:
  - src.projected_compression.mem_eff.CompressibleBlock
  - ${model.source_model.embedding._target_}
  - ${model.source_model.encoder.block_fn._target_}
  - ${model.source_model.head._target_}
  path_to_importances: /lustre/pd01/plgrid/plgllmefficont2/projected_compression/importances/8b/minitron_dimensions_importances.pt
  separate_block_optimizers: true
  source_model_for_distillation: false
  source_model_path: /lustre/pd01/plgrid/plgllmefficont2/projected_compression/hf_to_nano_converted/llama8b_in_nano.pt

trainer:
  _partial_: true
  _target_: src.projected_compression.trainer_distillation.PCDistillationTrainer
  checkpoint:
    load:
      model_checkpoint_filename: __model_checkpoint_filename.pt
      only_weights: true
      path: null
      training_state_filename: null
      type: nano
    save:
      interval: 0
      model_checkpoint_filename: __model_checkpoint_filename.pt
      path: /lustre/pd03/plgrid/plgllmefficont3/mstefaniak/checkpoints/results
      training_state_filename: __training_state_filename.pt
      type: hf_only
  distillation_alpha: 0.5
  distillation_temperature: 1.0
  distributed:
    fsdp2: null
  eval_dataloader: None
  eval_interval: 0
  gradient_accumulation_steps: 16
  gradient_clipping: 0.25
  learning_rate: 15
  n_eval_steps: 10
  n_steps: 4096
  only_compress_model_gradient_clipping: false
  only_target_model_gradient_clipping: 1.0
  original_llama_path: meta-llama/Llama-3.1-8B
  scheduler:
    _partial_: true
    _target_: src.core.schedulers.get_cosine_scheduler_with_warmup
    final_lr_fraction: 0.1
    warmup_steps: 40
  teacher_distributed:
    fsdp2:
      modules_to_shard:
      - ${distillation.teacher_model.embedding._target_}
      - ${distillation.teacher_model.encoder.block_fn._target_}
      - ${distillation.teacher_model.head._target_}
  train_dataloader:
    _target_: src.core.datasets.get_dataloader
    dataset:
      _target_: src.core.datasets.FineWebEduDataset
      path: ${cluster_switch.train_path_fineweb}
      seed: 123
      sequence_length: ${common.sequence_length}
      shuffle: true
      split: train
      tokenize_fn:
        _target_: src.core.datasets.llama_tokenize_fn
      use_new_sampling_method: true
      world_size_independent: false
    num_workers: 2
    total_batch_size: ${common.batch_size}
  weight_decay: 0.1
