_run_: true

cluster_switch:
  eval_path_c4: /storage_nvme_1/llm-random/datasets/c4/validation
  eval_path_fineweb: null
  train_path_c4: /storage_nvme_1/llm-random/datasets/c4/train
  train_path_fineweb: null

common:
  _target_: src.definitions.Common
  batch_size: 16
  datt: 64
  dff: 256
  dmodel: 64
  head_norm: true
  init_scale: 0.1
  init_type: truncated_normal_fixed
  kv_heads: 2
  model_type: gpt
  n_blocks: 4
  q_heads: 4
  sequence_length: 128
  vocab_size: 128256

evaluator:
  _partial_: true
  _target_: src.core.eval.Evaluator
  checkpoint_path: ${trainer.checkpoint.save.path}
  device: cuda
  limit: null
  tasks:
  - wikitext
  - piqa
  tokenizer: meta-llama/Llama-3.1-8B

infrastructure:
  cemetery_experiments_dir: ~/llmrandom_cemetery
  generated_configs_path: generated_configs
  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git
  metric_logger:
    _target_: src.definitions.MetricLoggerConfig
    heavy_metrics_calculation_interval: 100
    name: tiny_remote
    new_neptune_job: true
    project_name: pmtest/llm-random
    tags:
    - nano
    - remote
    - tiny
    type: neptune
  script:
  - PROJECT_HOME_PATH=/storage_nvme_2/projected_compression
  - "VENV_PATH=$PROJECT_HOME_PATH/pc_venv\nexport HF_HOME=$PROJECT_HOME_PATH/hf_cache\n\
    \n# Check if venv exists\nif [ ! -d \"$VENV_PATH\" ]; then\n  echo 'Virtual environment\
    \ not found. Creating...'\n  python3 -m venv \"$VENV_PATH\"\n  pip install --upgrade\
    \ pip\nfi \nsource \"$VENV_PATH/bin/activate\"\npip install --upgrade -r requirements.txt\n"
  server: entropy
  slurm:
    cpus_per_gpu: 16
    gres: gpu:1
    job-name: ${infrastructure.metric_logger.name}
    mem_per_gpu: 125G
    nodes: 1
    partition: a100
    time: 00:10:00

model:
  _target_: src.projected_compression.model.LLM
  embedding:
    _target_: src.projected_compression.model.TransformerEmbedding
    dmodel: ${common.dmodel}
    init_fn:
      _partial_: true
      _target_: src.projected_compression.model.trunc_normal_
    vocab_size: ${common.vocab_size}
  encoder:
    _target_: src.projected_compression.model.TransformerEncoder
    block_fn:
      _partial_: true
      _target_: src.projected_compression.model.TransformerBlock
      attention_fn:
        _partial_: true
        _target_: src.projected_compression.model.RoPEAttention
        dmodel: ${common.dmodel}
        k_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${eval:'(${common.datt} // ${model.encoder.block_fn.attention_fn.q_heads})
            * ${model.encoder.block_fn.attention_fn.kv_heads}'}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        kv_heads: ${common.kv_heads}
        o_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.datt}
          out_features: ${common.dmodel}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        q_heads: ${common.q_heads}
        q_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${common.datt}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        rope_base: 500000
        rope_scale_freqs: true
        seq_len: ${common.sequence_length}
        v_proj_fn: ${model.encoder.block_fn.attention_fn.k_proj_fn}
      ff_layer_fn:
        _partial_: true
        _target_: src.projected_compression.model.ProjectedLlamaFeedForward
        ff_post_act_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dff}
          out_features: ${common.dmodel}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        ff_pre_act_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${common.dff}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        gate_fn: ${model.encoder.block_fn.ff_layer_fn.ff_pre_act_fn}
      norm_fn:
        _partial_: true
        _target_: src.core.model.RMSNorm
        eps: 1.0e-05
        normalized_shape: ${common.dmodel}
    n_blocks: ${common.n_blocks}
  head:
    _target_: src.projected_compression.model.TransformerHead
    linear_fn:
      _partial_: true
      _target_: src.projected_compression.model.Linear
      in_features: ${common.dmodel}
      out_features: ${common.vocab_size}
      partial_init_fn:
        _partial_: true
        _target_: src.projected_compression.model.llm_random_weight_init
        scale: 1
    norm_fn:
      _partial_: true
      _target_: src.core.model.RMSNorm
      eps: 1.0e-05
      normalized_shape: ${common.dmodel}

overrides:
- trainer.learning_rate=0.005

trainer:
  _partial_: true
  _target_: src.core.trainer.Trainer
  checkpoint:
    load:
      model_checkpoint_filename: __model_checkpoint_filename.pt
      only_weights: true
      path: null
      training_state_filename: null
      type: nano
    save:
      interval: -1
      model_checkpoint_filename: __model_checkpoint_filename.pt
      path: checkpoint
      training_state_filename: __training_state_filename.pt
      type: huggingface
  distributed:
    fsdp2:
      modules_to_shard:
      - ${model.embedding._target_}
      - ${model.encoder.block_fn._target_}
      - ${model.head._target_}
  eval_dataloader:
    _target_: src.core.datasets.get_dataloader
    dataset_path: ${cluster_switch.eval_path_c4}
    dataset_split: validation
    dataset_type: c4
    num_workers: 8
    seed: 123
    sequence_length: ${common.sequence_length}
    shuffle: true
    tokenize_fn:
      _target_: src.core.datasets.llama_tokenize_fn
    total_batch_size: ${common.batch_size}
    use_new_sampling_method: true
    world_size_independent: false
  eval_interval: 100
  exp_learning_rate: null
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  learning_rate: 0.005
  n_eval_steps: 10
  n_steps: 100
  scheduler:
    _partial_: true
    _target_: src.core.schedulers.get_cosine_scheduler_with_warmup
    final_lr_fraction: 0.1
    warmup_steps: ${eval:'int(${trainer.n_steps} * 0.01)'}
  train_dataloader:
    _target_: src.core.datasets.get_dataloader
    dataset_path: ${cluster_switch.train_path_c4}
    dataset_split: train
    dataset_type: c4
    num_workers: 8
    seed: 1000
    sequence_length: ${common.sequence_length}
    shuffle: true
    tokenize_fn:
      _target_: src.core.datasets.llama_tokenize_fn
    total_batch_size: ${common.batch_size}
    use_new_sampling_method: true
    world_size_independent: false
  weight_decay: 0.1
