_run_: true

cluster_switch:
  eval_path_c4: /lustre/pd01/plgrid/plgllmefficont2/datasets/c4/validation
  eval_path_fineweb: /lustre/pd01/plgrid/plgllmefficont2/crewtool/proba2/fineweb-edu/train/train
  train_path_c4: /lustre/pd01/plgrid/plgllmefficont2/datasets/c4/train
  train_path_fineweb: /lustre/pd01/plgrid/plgllmefficont2/crewtool/proba2/fineweb-edu/train/train

common:
  _target_: src.definitions.Common
  batch_size: 64
  data_seed: 123
  datt: 1536
  dff: 3840
  dmodel: 1536
  head_norm: true
  init_scale: 0.1
  init_type: truncated_normal_fixed
  kv_heads: 24
  model_seed: 123
  model_type: gpt
  n_blocks: 24
  q_heads: 24
  sequence_length: 1024
  tokenizer: gpt2
  vocab_size: 50304

evaluator: null

infrastructure:
  cemetery_experiments_dir: ~/llmrandom_cemetery
  generated_configs_path: generated_configs
  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git
  max_concurrent_jobs: null
  metric_logger:
    heavy_metrics_calculation_interval: 100
    name: simpleP4_k24
    new_wandb_job: true
    project_name: llm-random-test
    tags:
    - nano
    - simpleP4
    - k24
    type: wandb
    wandb_entity: ideas_cv
  script:
  - ml CUDA/12.4.0
  - ${export_env_variables_placeholders:}
  - export PROJECT_HOME_PATH=/lustre/pd03/plgrid/plgllmefficont3/nano
  - export HYDRA_FULL_ERROR=1
  - export PIXI_HOME=$PROJECT_HOME_PATH/$USER/pixi
  - export HF_HOME=$PROJECT_HOME_PATH/$USER/hf_cache
  - export PATH="$HOME/.pixi/bin:$PATH"
  - export HF_DATASETS_TRUST_REMOTE_CODE=1
  - cd "$PIXI_HOME"
  - eval "$(pixi shell-hook)"
  - cd -
  server: lem
  slurm:
    cpus_per_gpu: 12
    gres: gpu:hopper:4
    job-name: ${infrastructure.metric_logger.name}
    mem_per_gpu: 90G
    nodes: 1
    partition: plgrid-lem-gpu-h100
    time: 0-04:00:00

model:
  _target_: src.core.model.LLM
  embedding:
    _target_: src.core.model.TransformerEmbedding
    dmodel: ${common.dmodel}
    init_fn:
      _partial_: true
      _target_: src.core.model.trunc_normal_
    vocab_size: ${common.vocab_size}
  encoder:
    _target_: src.core.model.TransformerEncoder
    block_fn:
      _partial_: true
      _target_: src.core.model.TransformerBlock
      attention_fn:
        _partial_: true
        _target_: src.core.model.RoPEAttention
        base_dmodel: ${oc.select:simpleP.base_model.dmodel,null}
        compile: true
        dmodel: ${common.dmodel}
        k_proj_fn:
          _partial_: true
          _target_: src.core.model.Linear
          in_features: ${common.dmodel}
          out_features: ${eval:'(${common.datt} // ${model.encoder.block_fn.attention_fn.q_heads})
            * ${model.encoder.block_fn.attention_fn.kv_heads}'}
          partial_init_fn:
            _partial_: true
            _target_: src.core.model.trunc_normal_init
            scale: ${common.init_scale}
        kv_heads: ${common.kv_heads}
        o_proj_fn:
          _partial_: true
          _target_: src.core.model.Linear
          in_features: ${common.datt}
          out_features: ${common.dmodel}
          partial_init_fn:
            _partial_: true
            _target_: src.core.model.trunc_normal_init
            scale: ${common.init_scale}
        pre_attn_fn:
          _partial_: true
          _target_: src.core.model.QKNorm
          k_norm_fn:
            _partial_: true
            _target_: src.core.model.RMSNorm
            eps: 1.0e-06
            normalized_shape: ${eval:'(${common.datt} // ${common.q_heads})'}
          q_norm_fn:
            _partial_: true
            _target_: src.core.model.RMSNorm
            eps: 1.0e-06
            normalized_shape: ${eval:'(${common.datt} // ${common.q_heads})'}
        q_heads: ${common.q_heads}
        q_proj_fn:
          _partial_: true
          _target_: src.core.model.Linear
          in_features: ${common.dmodel}
          out_features: ${common.datt}
          partial_init_fn:
            _partial_: true
            _target_: src.core.model.trunc_normal_init
            scale: ${common.init_scale}
        rope_base: 500000
        rope_scale_freqs: true
        seq_len: ${common.sequence_length}
        v_proj_fn: ${model.encoder.block_fn.attention_fn.k_proj_fn}
      ff_layer_fn:
        _partial_: true
        _target_: src.core.model.SwiGLU
        base_dff: ${oc.select:simpleP.base_model.dff,null}
        base_dmodel: ${oc.select:simpleP.base_model.dmodel,null}
        compile: false
        ff_post_act_fn:
          _partial_: true
          _target_: src.core.model.Linear
          in_features: ${common.dff}
          out_features: ${common.dmodel}
          partial_init_fn:
            _partial_: true
            _target_: src.core.model.trunc_normal_init
            scale: ${common.init_scale}
        ff_pre_act_fn:
          _partial_: true
          _target_: src.core.model.Linear
          in_features: ${common.dmodel}
          out_features: ${common.dff}
          partial_init_fn:
            _partial_: true
            _target_: src.core.model.trunc_normal_init
            scale: ${common.init_scale}
        gate_fn: ${model.encoder.block_fn.ff_layer_fn.ff_pre_act_fn}
      norm_fn:
        _partial_: true
        _target_: src.core.model.RMSNorm
        eps: 1.0e-05
        normalized_shape: ${common.dmodel}
    n_blocks: ${common.n_blocks}
  head:
    _target_: src.core.model.TransformerHead
    base_dmodel: ${oc.select:simpleP.base_model.dmodel,null}
    linear_fn:
      _partial_: true
      _target_: src.core.model.Linear
      in_features: ${common.dmodel}
      out_features: ${common.vocab_size}
      partial_init_fn:
        _partial_: true
        _target_: src.core.model.trunc_normal_init
        scale: ${common.init_scale}
    norm_fn:
      _partial_: true
      _target_: src.core.model.RMSNorm
      eps: 1.0e-05
      normalized_shape: ${common.dmodel}

overrides:
- trainer.learning_rate=7

simpleP:
  base_model:
    dff: 640
    dmodel: 256

trainer:
  _partial_: true
  _target_: src.core.trainer.Trainer
  checkpoint:
    load:
      model_checkpoint_filename: __model_checkpoint_filename.pt
      only_weights: true
      path: null
      reset_scheduler: false
      rewind_data: false
      training_state_filename: null
      type: nano
    save:
      interval: -1
      model_checkpoint_filename: __model_checkpoint_filename.pt
      path: null
      training_state_filename: __training_state_filename.pt
      type: nano
  distributed:
    fsdp2:
      modules_to_shard:
      - ${model.embedding._target_}
      - ${model.encoder.block_fn._target_}
      - ${model.head._target_}
  eval_dataloader:
    _target_: src.context_scaling.dataset.get_dataloader
    dataset:
      _target_: src.context_scaling.dataset.AbstractDataset
      data_generator:
        _partial_: true
        _target_: src.context_scaling.dataset.get_dataset
        load_dataset_fn: null
        path: ${cluster_switch.eval_path_c4}
        shuffle: true
      sample_packer_fn:
        _partial_: true
        _target_: src.context_scaling.dataset.new_packer
      seed: ${common.data_seed}
      sequence_length: ${common.sequence_length}
      tokenize_fn:
        _target_: src.core.datasets.gpt2_tokenize_fn
      use_new_sampling_method: true
      world_size_independent: false
    num_workers: 0
    total_batch_size: ${common.batch_size}
  eval_interval: 500
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  learning_rate: 7
  n_eval_steps: 10
  n_steps: 5001
  scheduler:
    _partial_: true
    _target_: src.core.schedulers.WSDScheduler
    decay_steps: ${eval:'int(${trainer.n_steps} * 0.1)'}
    n_steps: ${trainer.n_steps}
    warmup_steps: ${eval:'int(${trainer.n_steps} * 0.01)'}
  train_dataloader:
    _target_: src.context_scaling.dataset.get_dataloader
    dataset:
      _target_: src.context_scaling.dataset.AbstractDataset
      data_generator:
        _partial_: true
        _target_: src.context_scaling.dataset.get_dataset
        load_dataset_fn: null
        path: ${cluster_switch.train_path_c4}
        shuffle: true
      sample_packer_fn:
        _partial_: true
        _target_: src.context_scaling.dataset.new_packer
      seed: ${common.data_seed}
      sequence_length: ${common.sequence_length}
      tokenize_fn:
        _target_: src.core.datasets.gpt2_tokenize_fn
      use_new_sampling_method: true
      world_size_independent: false
    num_workers: 0
    total_batch_size: ${common.batch_size}
  weight_decay: 0.1
