_run_: true

cluster_switch:
  eval_path_c4: /net/scratch/hscra/plgrid/plgmaciejpioro/c4/validation
  eval_path_fineweb: /net/scratch/hscra/plgrid/plgmaciejpioro/fineweb-edu/train/train
  train_path_c4: /net/scratch/hscra/plgrid/plgmaciejpioro/c4/train
  train_path_fineweb: /net/scratch/hscra/plgrid/plgmaciejpioro/fineweb-edu/train/train

common:
  _target_: src.definitions.Common
  batch_size: 64
  datt: ${common.dmodel}
  dff: 2724
  dmodel: 1024
  head_norm: true
  init_scale: 0.1
  init_type: truncated_normal_fixed
  kv_heads: 16
  model_type: gpt
  n_blocks: 16
  q_heads: 16
  sequence_length: 1024
  vocab_size: 50304

evaluator: null

infrastructure:
  cemetery_experiments_dir: ~/llmrandom_cemetery
  generated_configs_path: generated_configs
  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git
  max_concurrent_jobs: null
  metric_logger:
    heavy_logging_layers:
    - 0
    - 10
    - 15
    heavy_metrics_calculation_interval: 1000
    name: pk_mlm_init_only_keys_warmup01
    new_neptune_job: true
    new_wandb_job: true
    project_name: tml-bgw
    tags:
    - nano
    - pk_mlm
    - 2026.03.24
    - warmup_steps=${trainer.scheduler.warmup_steps}
    - learned_embeddings
    - QKNorm
    - initialization_grid
    - init_scale_${common.init_scale}
    - init_only_keys
    - lr=${trainer.learning_rate}
    - seq_len=${common.sequence_length}
    - n_layers=${common.n_blocks}
    - dmodel=${common.dmodel}
    - seed=${trainer.train_dataloader.dataset.seed}
    type: wandb
    wandb_entity: ideas_cv
  script:
  - ${export_env_variables_placeholders:}
  - module load ML-bundle/25.04
  - export PROJECT_HOME_PATH=$PLG_GROUPS_STORAGE/plggllmeffi/nano
  - export HF_HOME=$PROJECT_HOME_PATH/hf_cache
  - export HYDRA_FULL_ERROR=1
  - export PIXI_HOME=$PROJECT_HOME_PATH/pixi
  - export PATH="$HOME/.pixi/bin:$PATH"
  - export XDG_DATA_HOME="PROJECT_HOME_PATH/data"
  - export XDG_CACHE_HOME="$PROJECT_HOME_PATH/cache"
  - export XDG_STATE_HOME="$PROJECT_HOME_PATH/state"
  - cd "$PIXI_HOME"
  - eval "$(pixi shell-hook)"
  - cd -
  server: helios
  slurm:
    cpus_per_gpu: 12
    gres: gpu:2
    job-name: ${infrastructure.metric_logger.name}
    mem_per_gpu: 90G
    nodes: 1
    partition: plgrid-gpu-gh200
    time: 1-00:00:00

model:
  _target_: src.projected_compression.model.LLM
  embedding:
    _target_: src.projected_compression.model.TransformerEmbedding
    dmodel: ${common.dmodel}
    init_fn:
      _partial_: true
      _target_: src.projected_compression.model.trunc_normal_
    vocab_size: ${common.vocab_size}
  encoder:
    _target_: src.projected_compression.model.TransformerEncoder
    block_fn:
      _partial_: true
      _target_: src.projected_compression.model.TransformerBlock
      attention_fn:
        _partial_: true
        _target_: src.product_keys.model.RoPEProductKeysEncoderAttention
        dmodel: ${common.dmodel}
        init_scale: ${common.init_scale}
        k_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${eval:'(${common.datt} // ${model.encoder.block_fn.attention_fn.q_heads})
            * ${model.encoder.block_fn.attention_fn.kv_heads}'}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: ${common.init_scale}
        kv_heads: ${common.kv_heads}
        o_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.datt}
          out_features: ${common.dmodel}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        q_heads: ${common.q_heads}
        q_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${common.datt}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        rope_base: 500000
        rope_scale_freqs: true
        seq_len: ${common.sequence_length}
        top_k: 16
        v_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${eval:'(${common.datt} // ${model.encoder.block_fn.attention_fn.q_heads})
            * ${model.encoder.block_fn.attention_fn.kv_heads}'}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
      ff_layer_fn:
        _partial_: true
        _target_: src.projected_compression.model.ProjectedLlamaFeedForward
        ff_post_act_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dff}
          out_features: ${common.dmodel}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        ff_pre_act_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${common.dff}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        gate_fn: ${model.encoder.block_fn.ff_layer_fn.ff_pre_act_fn}
      norm_fn:
        _partial_: true
        _target_: src.core.model.RMSNorm
        eps: 1.0e-05
        normalized_shape: ${common.dmodel}
    n_blocks: ${common.n_blocks}
  head:
    _target_: src.projected_compression.model.TransformerHead
    linear_fn:
      _partial_: true
      _target_: src.projected_compression.model.Linear
      in_features: ${common.dmodel}
      out_features: ${common.vocab_size}
      partial_init_fn:
        _partial_: true
        _target_: src.projected_compression.model.llm_random_weight_init
        scale: 1
    norm_fn:
      _partial_: true
      _target_: src.core.model.RMSNorm
      eps: 1.0e-05
      normalized_shape: ${common.dmodel}

overrides:
- common.init_scale=0.1

trainer:
  _partial_: true
  _target_: src.product_keys.trainer.MaskedLMTrainer
  checkpoint:
    load:
      model_checkpoint_filename: __model_checkpoint_filename.pt
      only_weights: true
      path: null
      training_state_filename: null
      type: nano
    save:
      interval: -1
      model_checkpoint_filename: __model_checkpoint_filename.pt
      path: null
      training_state_filename: __training_state_filename.pt
      type: nano
  distributed:
    fsdp2:
      modules_to_shard:
      - ${model.embedding._target_}
      - ${model.encoder.block_fn._target_}
      - ${model.head._target_}
  eval_dataloader:
    _target_: src.core.datasets.get_dataloader
    dataset:
      _target_: src.core.datasets.C4Dataset
      path: ${cluster_switch.eval_path_c4}
      seed: 123
      sequence_length: ${common.sequence_length}
      shuffle: true
      split: validation
      tokenize_fn:
        _target_: src.product_keys.datasets.gpt2_mask_tokenize_fn
      use_new_sampling_method: true
      world_size_independent: false
    num_workers: 8
    total_batch_size: ${common.batch_size}
  eval_interval: 100
  gradient_accumulation_steps: 4
  gradient_clipping: 1.0
  learning_rate: 0.002
  mask_token_id: 50257
  masking_percentage: 0.2
  n_eval_steps: 10
  n_steps: 15000
  scheduler:
    _partial_: true
    _target_: src.core.schedulers.get_cosine_scheduler_with_warmup
    final_lr_fraction: 0.1
    warmup_steps: ${eval:'int(${trainer.n_steps} * 0.10)'}
  train_dataloader:
    _target_: src.core.datasets.get_dataloader
    dataset:
      _target_: src.core.datasets.C4Dataset
      path: ${cluster_switch.train_path_c4}
      seed: 42
      sequence_length: ${common.sequence_length}
      shuffle: true
      split: train
      tokenize_fn:
        _target_: src.product_keys.datasets.gpt2_mask_tokenize_fn
      use_new_sampling_method: true
      world_size_independent: false
    num_workers: 8
    total_batch_size: ${common.batch_size}
  unmaskable_special_tokens:
  - 50256
  - 50257
  weight_decay: 0.1
