_run_: true

apply_functions:
- _partial_: true
  _target_: src.projected_compression.weight_importances.dummy_importances
  checkpoint_save_path: ${trainer.checkpoint.save.path}
  dff: ${common.dff}
  dmodel: ${common.dmodel}
  n_blocks: ${model.encoder.n_blocks}
- _partial_: true
  _target_: src.projected_compression.weight_importances.minitron_importances
  calibration_dataset_size: 8192
  checkpoint_save_path: ${trainer.checkpoint.save.path}
  dataloader: ${trainer.train_dataloader}
  dff: ${common.dff}
  dmodel: ${common.dmodel}
  n_blocks: ${model.encoder.n_blocks}
  seq_len: ${common.sequence_length}
  total_batch_size: ${trainer.train_dataloader.total_batch_size}
- _partial_: true
  _target_: src.projected_compression.weight_importances.magnitude_importances
  checkpoint_save_path: ${trainer.checkpoint.save.path}
  dff: ${common.dff}
  dmodel: ${common.dmodel}
  n_blocks: ${model.encoder.n_blocks}
- _partial_: true
  _target_: src.core.utils.finish_exp

cluster_switch:
  eval_path_c4: /storage_nvme_1/llm-random/datasets/c4/validation
  eval_path_fineweb: /storage_nvme_4/llm-random/datasets/fineweb/train
  train_path_c4: /storage_nvme_1/llm-random/datasets/c4/train
  train_path_fineweb: /storage_nvme_4/llm-random/datasets/fineweb/train

common:
  _target_: src.definitions.Common
  batch_size: 4
  datt: 2048
  dff: 8192
  dmodel: 2048
  head_norm: true
  init_scale: 0.1
  init_type: truncated_normal_fixed
  kv_heads: 8
  model_type: gpt
  n_blocks: 16
  q_heads: 32
  sequence_length: 1024
  vocab_size: 128256

evaluator: null

infrastructure:
  cemetery_experiments_dir: ~/llmrandom_cemetery
  generated_configs_path: generated_configs
  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git
  max_concurrent_jobs: null
  metric_logger:
    heavy_metrics_calculation_interval: 100
    name: Llame_importances
    new_wandb_job: true
    project_name: llm-random-test
    tags:
    - nano
    - pc
    - llama_1
    - IMPORTANCES
    - fineweb
    type: wandb
    wandb_entity: ideas_cv
  script:
  - ${export_env_variables_placeholders:}
  - export PROJECT_HOME_PATH=/storage_nvme_4/nano
  - export HF_HOME=$PROJECT_HOME_PATH/hf_cache
  - export HYDRA_FULL_ERROR=1
  - export PIXI_HOME=$PROJECT_HOME_PATH/$USER/pixi
  - export PATH="$HOME/.pixi/bin:$PATH"
  - export XDG_DATA_HOME="$PIXI_HOME/data"
  - export XDG_CACHE_HOME="$PIXI_HOME/cache"
  - export XDG_STATE_HOME="$PIXI_HOME/state"
  - cd "$PIXI_HOME"
  - eval "$(pixi shell-hook)"
  - cd -
  server: entropy
  slurm:
    cpus_per_gpu: 14
    gres: gpu:1
    job-name: importances_llama_1
    mem_per_gpu: 90G
    nodes: 1
    partition: h100
    time: 0-2:00:00

model:
  _target_: src.projected_compression.model.LLM
  embedding:
    _target_: src.projected_compression.model.TransformerEmbedding
    dmodel: ${common.dmodel}
    init_fn:
      _partial_: true
      _target_: src.projected_compression.model.trunc_normal_
    vocab_size: ${common.vocab_size}
  encoder:
    _target_: src.projected_compression.model.TransformerEncoder
    block_fn:
      _partial_: true
      _target_: src.projected_compression.model.TransformerBlock
      attention_fn:
        _partial_: true
        _target_: src.projected_compression.model.RoPEAttention
        dmodel: ${common.dmodel}
        k_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${eval:'(${common.datt} // ${model.encoder.block_fn.attention_fn.q_heads})
            * ${model.encoder.block_fn.attention_fn.kv_heads}'}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        kv_heads: ${common.kv_heads}
        o_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.datt}
          out_features: ${common.dmodel}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        q_heads: ${common.q_heads}
        q_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${common.datt}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        rope_base: 500000
        rope_scale_freqs: true
        seq_len: ${common.sequence_length}
        v_proj_fn: ${model.encoder.block_fn.attention_fn.k_proj_fn}
      ff_layer_fn:
        _partial_: true
        _target_: src.projected_compression.model.ProjectedLlamaFeedForward
        ff_post_act_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dff}
          out_features: ${common.dmodel}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        ff_pre_act_fn:
          _partial_: true
          _target_: src.projected_compression.model.Linear
          in_features: ${common.dmodel}
          out_features: ${common.dff}
          partial_init_fn:
            _partial_: true
            _target_: src.projected_compression.model.llm_random_weight_init
            scale: 1
        gate_fn: ${model.encoder.block_fn.ff_layer_fn.ff_pre_act_fn}
      norm_fn:
        _partial_: true
        _target_: src.core.model.RMSNorm
        eps: 1.0e-05
        normalized_shape: ${common.dmodel}
    n_blocks: ${common.n_blocks}
  head:
    _target_: src.projected_compression.model.TransformerHead
    linear_fn:
      _partial_: true
      _target_: src.projected_compression.model.Linear
      in_features: ${common.dmodel}
      out_features: ${common.vocab_size}
      partial_init_fn:
        _partial_: true
        _target_: src.projected_compression.model.llm_random_weight_init
        scale: 1
    norm_fn:
      _partial_: true
      _target_: src.core.model.RMSNorm
      eps: 1.0e-05
      normalized_shape: ${common.dmodel}

overrides: []

trainer:
  _partial_: true
  _target_: src.core.trainer.Trainer
  checkpoint:
    load:
      model_checkpoint_filename: __model_checkpoint_filename.pt
      only_weights: true
      path: meta-llama/Llama-3.2-1B
      training_state_filename: null
      type: huggingface
    save:
      interval: -1
      model_checkpoint_filename: __model_checkpoint_filename.pt
      path: /lustre/pd03/plgrid/plgllmefficont3/plgj321m/pc/importances/1b
      training_state_filename: __training_state_filename.pt
      type: nano
  distributed:
    fsdp2:
      modules_to_shard:
      - ${model.embedding._target_}
      - ${model.encoder.block_fn._target_}
      - ${model.head._target_}
  eval_dataloader:
    _target_: src.core.datasets.get_dataloader
    dataset:
      _target_: src.core.datasets.FineWebEduDataset
      path: ${cluster_switch.eval_path_fineweb}
      seed: 123
      sequence_length: ${common.sequence_length}
      shuffle: true
      split: train
      tokenize_fn:
        _target_: src.core.datasets.llama_tokenize_fn
      use_new_sampling_method: true
      world_size_independent: false
    num_workers: 2
    total_batch_size: ${common.batch_size}
  eval_interval: 100
  gradient_accumulation_steps: 8
  gradient_clipping: 1.0
  learning_rate: 1
  n_eval_steps: 10
  n_steps: 0
  scheduler:
    _partial_: true
    _target_: src.core.schedulers.get_cosine_scheduler_with_warmup
    final_lr_fraction: 0.1
    warmup_steps: ${eval:'int(${trainer.n_steps} * 0.01)'}
  train_dataloader:
    _target_: src.core.datasets.get_dataloader
    dataset:
      _target_: src.core.datasets.FineWebEduDataset
      path: ${cluster_switch.train_path_fineweb}
      seed: 123
      sequence_length: ${common.sequence_length}
      shuffle: true
      split: train
      tokenize_fn:
        _target_: src.core.datasets.llama_tokenize_fn
      use_new_sampling_method: true
      world_size_independent: false
    num_workers: 2
    total_batch_size: ${common.batch_size}
  weight_decay: 0.1
