_run_: true

apply_functions:
- _partial_: true
  _target_: src.projected_compression.compression.init_compression
  dimensions_importances_path: /home/m1kush/llmrandom_cemetery/SmolLM_1700_importances_2026-03-28_15-44-28/None/144636/0/minitron_dimensions_importances.pt
  target_dff: ${common.dff}
  target_dmodel: ${common.dmodel}

cluster_switch:
  eval_path_c4: /storage_nvme_1/llm-random/datasets/c4/validation
  eval_path_fineweb: /storage_nvme_4/llm-random/datasets/fineweb/train
  train_path_c4: /storage_nvme_1/llm-random/datasets/c4/train
  train_path_fineweb: /storage_nvme_4/llm-random/datasets/fineweb/train

common:
  _target_: src.definitions.Common
  base_dff: 8192
  base_dmodel: 2048
  batch_size: 512
  dff: 1728
  dhead: 64
  dmodel: 448
  kv_heads: 32
  n_blocks: 24
  q_heads: 32
  sequence_length: 1024
  vocab_size: 49152

common_distillation:
  datt: 2048
  dff: 8192
  dmodel: 2048
  kv_heads: 32
  n_blocks: 24
  q_heads: 32
  vocab_size: 49152

distillation:
  load:
    path: HuggingFaceTB/SmolLM-1.7B
    type: huggingface
  teacher_model:
    _target_: src.projected_compression.model.LLM
    embedding:
      _target_: src.projected_compression.model.TransformerEmbedding
      dmodel: ${common_distillation.dmodel}
      init_fn:
        _partial_: true
        _target_: src.projected_compression.model.trunc_normal_
      vocab_size: ${common_distillation.vocab_size}
    encoder:
      _target_: src.projected_compression.model.TransformerEncoder
      block_fn:
        _partial_: true
        _target_: src.projected_compression.model.TransformerBlock
        attention_fn:
          _partial_: true
          _target_: src.projected_compression.model.RoPEAttention
          dmodel: ${common_distillation.dmodel}
          k_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.dmodel}
            out_features: ${eval:'(${common_distillation.datt} // ${distillation.teacher_model.encoder.block_fn.attention_fn.q_heads})
              * ${distillation.teacher_model.encoder.block_fn.attention_fn.kv_heads}'}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          kv_heads: ${common_distillation.kv_heads}
          o_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.datt}
            out_features: ${common_distillation.dmodel}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          q_heads: ${common_distillation.q_heads}
          q_proj_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.dmodel}
            out_features: ${common_distillation.datt}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          rope_base: 500000
          rope_scale_freqs: true
          seq_len: ${common.sequence_length}
          v_proj_fn: ${distillation.teacher_model.encoder.block_fn.attention_fn.k_proj_fn}
        ff_layer_fn:
          _partial_: true
          _target_: src.projected_compression.model.ProjectedLlamaFeedForward
          ff_post_act_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.dff}
            out_features: ${common_distillation.dmodel}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          ff_pre_act_fn:
            _partial_: true
            _target_: src.projected_compression.model.Linear
            in_features: ${common_distillation.dmodel}
            out_features: ${common_distillation.dff}
            partial_init_fn:
              _partial_: true
              _target_: src.projected_compression.model.llm_random_weight_init
              scale: 1
          gate_fn: ${distillation.teacher_model.encoder.block_fn.ff_layer_fn.ff_pre_act_fn}
        norm_fn:
          _partial_: true
          _target_: src.core.model.RMSNorm
          eps: 1.0e-05
          normalized_shape: ${common_distillation.dmodel}
      n_blocks: ${common_distillation.n_blocks}
    head:
      _target_: src.projected_compression.model.TransformerHead
      linear_fn:
        _partial_: true
        _target_: src.projected_compression.model.Linear
        in_features: ${common_distillation.dmodel}
        out_features: ${common_distillation.vocab_size}
        partial_init_fn:
          _partial_: true
          _target_: src.projected_compression.model.llm_random_weight_init
          scale: 1
      norm_fn:
        _partial_: true
        _target_: src.core.model.RMSNorm
        eps: 1.0e-05
        normalized_shape: ${common_distillation.dmodel}

evaluator: null

infrastructure:
  cemetery_experiments_dir: ~/llmrandom_cemetery
  generated_configs_path: generated_configs
  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git
  max_concurrent_jobs: null
  metric_logger:
    heavy_metrics_calculation_interval: 100
    name: fineweb-edu-dedup-debug
    new_wandb_job: true
    project_name: pc_smollm
    tags:
    - nano
    - pc
    - smollm_1700
    - projected_compression
    - distillation
    - 90p
    - 2B_tokens
    - lr_grid
    type: wandb
    wandb_entity: ideas_cv
  script:
  - ${export_env_variables_placeholders:}
  - export PROJECT_HOME_PATH=/storage_nvme_4/nano
  - export HF_HOME=$PROJECT_HOME_PATH/hf_cache
  - export HYDRA_FULL_ERROR=1
  - export PIXI_HOME=/storage_nvme_4/nano/pixi_md
  - export PATH="$PIXI_HOME/bin:$PATH"
  - export XDG_DATA_HOME="$PIXI_HOME/data"
  - export XDG_CACHE_HOME="$PIXI_HOME/cache"
  - export XDG_STATE_HOME="$PIXI_HOME/state"
  - cd "$PIXI_HOME"
  - eval "$(pixi shell-hook)"
  - cd -
  server: entropy
  slurm:
    cpus_per_gpu: 14
    gres: gpu:4
    job-name: ${infrastructure.metric_logger.name}
    mem_per_gpu: 90G
    nodes: 1
    partition: h100
    time: 0-24:00:00

model:
  _target_: src.projected_compression.model.LLM
  embedding:
    _target_: src.projected_compression.model.ProjectedEmbedding
    embedding_dim: ${common.base_dmodel}
    num_embeddings: ${common.vocab_size}
    result_out_features: ${common.dmodel}
  encoder:
    _target_: src.projected_compression.model.TransformerEncoder
    block_fn:
      _partial_: true
      _target_: src.projected_compression.model.TransformerBlock
      attention_fn:
        _partial_: true
        _target_: src.projected_compression.model.RoPEAttention
        dmodel: ${common.base_dmodel}
        factor: 32
        high_freq_factor: 4
        k_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.ProjectedLinear
          base_in_features: ${common.base_dmodel}
          base_out_features: ${eval:'${model.encoder.block_fn.attention_fn.kv_heads}
            * ${common.dhead}'}
          result_in_features: ${common.dmodel}
          result_out_features: null
        kv_heads: ${common.kv_heads}
        low_freq_factor: 1
        o_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.ProjectedLinear
          base_in_features: ${eval:'${model.encoder.block_fn.attention_fn.q_heads}
            * ${common.dhead}'}
          base_out_features: ${common.base_dmodel}
          result_in_features: null
          result_out_features: ${common.dmodel}
        original_max_position_embeddings: 8192
        q_heads: ${common.q_heads}
        q_proj_fn:
          _partial_: true
          _target_: src.projected_compression.model.ProjectedLinear
          base_in_features: ${common.base_dmodel}
          base_out_features: ${eval:'${model.encoder.block_fn.attention_fn.q_heads}
            * ${common.dhead}'}
          result_in_features: ${common.dmodel}
          result_out_features: null
        rope_base: 10000
        rope_scale_freqs: true
        seq_len: ${common.sequence_length}
        v_proj_fn: ${model.encoder.block_fn.attention_fn.k_proj_fn}
      ff_layer_fn:
        _partial_: true
        _target_: src.projected_compression.model.ProjectedLlamaFeedForward
        ff_post_act_fn:
          _partial_: true
          _target_: src.projected_compression.model.ProjectedLinear
          base_in_features: ${common.base_dff}
          base_out_features: ${common.base_dmodel}
          result_in_features: ${common.dff}
          result_out_features: ${common.dmodel}
        ff_pre_act_fn:
          _partial_: true
          _target_: src.projected_compression.model.ProjectedLinear
          base_in_features: ${common.base_dmodel}
          base_out_features: ${common.base_dff}
          result_in_features: ${common.dmodel}
          result_out_features: ${common.dff}
        gate_fn: ${model.encoder.block_fn.ff_layer_fn.ff_pre_act_fn}
      norm_fn:
        _partial_: true
        _target_: src.core.model.RMSNorm
        eps: 1.0e-05
        normalized_shape: ${common.base_dmodel}
    n_blocks: ${common.n_blocks}
  head:
    _target_: src.projected_compression.model.TransformerHead
    linear_fn:
      _partial_: true
      _target_: src.projected_compression.model.ProjectedLinear
      base_in_features: ${common.base_dmodel}
      base_out_features: ${common.vocab_size}
      result_in_features: ${common.dmodel}
      result_out_features: null
    norm_fn:
      _partial_: true
      _target_: src.core.model.RMSNorm
      eps: 1.0e-05
      normalized_shape: ${common.base_dmodel}

overrides:
- trainer.train_dataloader.seed=1000
- trainer.eval_dataloader.seed=42
- trainer.n_steps=4096
- trainer.learning_rate=10

trainer:
  _partial_: true
  _target_: src.core.trainer_distillation.TrainerDistillation
  checkpoint:
    load:
      model_checkpoint_filename: __model_checkpoint_filename.pt
      only_weights: true
      path: HuggingFaceTB/SmolLM-1.7B
      training_state_filename: null
      type: huggingface
    save:
      interval: ${eval:'${trainer.n_steps} - 1'}
      model_checkpoint_filename: __model_checkpoint_filename.pt
      path: /storage_nvme_1/md/checkpoints
      training_state_filename: __training_state_filename.pt
      type: nano
  distillation_alpha: 0.5
  distillation_temperature: 1.0
  distributed:
    fsdp2:
      modules_to_shard:
      - ${model.embedding._target_}
      - ${model.encoder.block_fn._target_}
      - ${model.head._target_}
  eval_dataloader:
    _target_: src.core.datasets.get_mixture_of_datasets_dataloader
    dataset_split: validation
    datasets:
    - eval_fraction: 0.1
      path: /storage_nvme_1/llm-random/datasets/fineweb-edu-dedup/train
      weight: 1.0
    num_workers: 1
    seed: 42
    sequence_length: ${common.sequence_length}
    shuffle: true
    tokenize_fn:
      _target_: src.core.datasets.get_tokenize_fn
      model_name: HuggingFaceTB/SmolLM-1.7B
    total_batch_size: ${common.batch_size}
    use_new_sampling_method: true
    world_size_independent: false
  eval_interval: 50
  gradient_accumulation_steps: 8
  gradient_clipping: 1.0
  learning_rate: 10
  n_eval_steps: 10
  n_steps: 4096
  per_dataset_dataloaders:
    _target_: src.core.datasets.get_per_dataset_dataloaders
    datasets: ${trainer.eval_dataloader.datasets}
    num_workers: ${trainer.eval_dataloader.num_workers}
    seed: ${trainer.eval_dataloader.seed}
    sequence_length: ${common.sequence_length}
    shuffle: ${trainer.eval_dataloader.shuffle}
    tokenize_fn: ${trainer.eval_dataloader.tokenize_fn}
    total_batch_size: ${common.batch_size}
  scheduler:
    _partial_: true
    _target_: src.core.schedulers.get_cosine_scheduler_with_warmup
    final_lr_fraction: 0.1
    warmup_steps: 40
  teacher_distributed:
    fsdp2:
      modules_to_shard:
      - ${distillation.teacher_model.embedding._target_}
      - ${distillation.teacher_model.encoder.block_fn._target_}
      - ${distillation.teacher_model.head._target_}
  train_dataloader:
    _target_: src.core.datasets.get_mixture_of_datasets_dataloader
    dataset_split: train
    datasets:
    - eval_fraction: 0.1
      path: /storage_nvme_1/llm-random/datasets/fineweb-edu-dedup/train
      weight: 1.0
    num_workers: 2
    seed: 1000
    sequence_length: ${common.sequence_length}
    shuffle: true
    tokenize_fn:
      _target_: src.core.datasets.get_tokenize_fn
      model_name: HuggingFaceTB/SmolLM-1.7B
    total_batch_size: ${common.batch_size}
    use_new_sampling_method: true
    world_size_independent: false
  weight_decay: 0.1
