defaults:
  - _misc@_here_: default
  - _dataset@_here_: fineweb
  - _cluster@_here_: helios
  - _model/llama@_here_: projected_1B
  - _trainer@_here_: llama

  - _checkpoints@_here_: none


infrastructure:
  slurm:
    gres: gpu:4
    nodes: 2
    job_name: test_job
  experiment_prepare_venv_path:   /net/scratch/hscra/plgrid/plgcrewtool/prepare_venv/bin/activate # /net/storage/pr3/plgrid/plggllmeffi/tr_venv/bin/activate # $HOME/nano/.venv/bin/activate
  venv_path: /net/scratch/hscra/plgrid/plgcrewtool/venv_test3/bin/activate
  server: mojhelios

common: 
  batch_size: 32
  sequence_length: 2048

trainer:
  n_steps: 100
  learning_rate: 5e-5
  
  checkpoint:
    load:
      type: huggingface
      path: "meta-llama/Llama-3.2-1B"