defaults:
  # - _cluster@_here_: entropy
  - _cluster@_here_: helios
  - _model@_here_: llama_3_1
  - _trainer@_here_: llama
  - _dataset@_here_: c4
  - _checkpoints@_here_: none
  - _misc@_here_: default

common: 
  batch_size: 512

trainer:
  n_steps: 0
  learning_rate: 0.0000610352
  gradient_accumulation_steps: 1

  checkpoint:
   load:
    type: nano
    path:  # change
   save:
    type: huggingface
    # path: /storage_nvme_3/crewtool/nano_checkpoints/llama1_ta3/ # entropy_m
    path: /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/results/llama1_50 # helios
  
infrastructure:
  server: entropym
  metric_logger:
    name: test
    tags:
      - pc
      - nano
      - hf_conversion
      - llama1_50_pc_3b
      # - llama1_50_hp

  slurm: 
    gres: gpu:4

