defaults:
  # - _cluster@_here_: helios_4
  - _cluster@_here_: entropy
  - _model@_here_: llama_3_1
  - _trainer@_here_: llama
  - _dataset@_here_: c4
  # - _dataset@_here_: fineweb
  - _checkpoints@_here_: none
  - _misc@_here_: default
  - _mas@_here_: crewtool


common:
  sequence_length: 1024
  batch_size: 512

  # 50%
  dmodel: 1344
  dff: 5376


trainer:
  gradient_accumulation_steps: 8
  # n_steps: 2048
  n_steps: 101
  # ^n_steps: 
    # - 4096
    # - 6144
    # - 8192

  # learning_rate: 0001220703125 # 0.00048828125, 0.000244140625, 0.0001220703125, 6.103515625e-05, 3.0517578125e-05, 1.52587890625e-05
  ^learning_rate: 
    # - 0.0001220703125
    - 0.000244140625


  checkpoint:
   load:
    type: nano
    path: /storage_nvme_3/crewtool/nano_checkpoints/tmp/65529/0/step_-1
    # path: /storage_nvme_3/crewtool/nano_checkpoints/tmp/65526/0/step_-1
   save:
    type: nano
    path: /storage_nvme_3/crewtool/nano_checkpoints/tmp #change
  

infrastructure:
  metric_logger:
    name: Llame_PC
    tags:
      - nano
      - pc
      - llama_1

  slurm:
    gres: gpu:4


