defaults:
  # - _cluster@_here_: helios
  - _cluster@_here_: entropy
  - _model@_here_: llama_3_1
  - _trainer@_here_: llama
  - _dataset@_here_: fineweb
  - _checkpoints@_here_: none
  - _misc@_here_: default
  - _mas@_here_: crewtool


common:
  sequence_length: 1024
  # sequence_length: 100
  batch_size: 512 #dev
  # batch_size: 16 #dev


trainer:
  gradient_accumulation_steps: 8 #dev
  # gradient_accumulation_steps: 1 #dev
  # n_steps: 2048
  # n_steps: 401
  # n_steps: 101
  ^n_steps: 
    # - 101
    # - 2048
    - 4096
    # - 6144
    # - 8192
    # - 16384

  exp_learning_rate: 12 #optimal fo 1B
  # ^exp_learning_rate: 
  #   - 13
  #   - 12
  #   - 11

  scheduler:
    warmup_steps: 40

  checkpoint:
   load:
    type: huggingface
    path: "meta-llama/Llama-3.2-1B"
   save:  
    type: nano
    path: /storage_nvme_3/crewtool/nano_checkpoints/tmp # entropy
    # path: /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem # helios

  # train_dataloader:
    # ^num_workers: 
    #   - 1
    #   - 2
    #   - 3
    #   - 4
    #   - 5
    # seed: 1
    # shuffle: true
    # use_new_sampling_method: true

  # eval_dataloader:
    # num_workers: 1
    # seed: 123
    # shuffle: true
    # use_new_sampling_method: true


infrastructure:
  metric_logger:
    name: Llame_HP
    tags:
      - nano
      - pc
      - llama_1
      - hard_pruning
      - workers_grid

  slurm:
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4 #dev
    time: "0-8:00:00"
 
apply_functions:
  - _target_: src.projected_compression.pruning.prune
    _partial_: true
    # dimensions_importances_path: /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/pc/fw_importances_8m/minitron_dimensions_importances.pt # helios
    dimensions_importances_path: /storage_nvme_3/crewtool/pc/fw_importances_8m/minitron_dimensions_importances.pt # entropy
    target_dmodel: 1344
    target_dff: 5376

