defaults:
  # - _cluster@_here_: helios
  - _cluster@_here_: entropy
  - _model/llmrandom@_here_: projected_800
  - _trainer@_here_: llama
  # - _dataset@_here_: fineweb
  - _dataset@_here_: c4
  - _checkpoints@_here_: none
  - _misc@_here_: default


common:
  sequence_length: 512
  batch_size: 512
  # dmodel: 768 # 36
  # dff: 3072
  # dmodel: 1152 # 65
  # dff: 4608


trainer:
  gradient_accumulation_steps: 4
  ^n_steps: 
    # - 101
    - 4000
    # - 8000
    # - 16000
    # - 24000

  # exp_learning_rate: asd # optimal 10%
  # exp_learning_rate: 13 # optimal 30%
  # exp_learning_rate: 14 # optimal 1B 50%
  # exp_learning_rate: 15 # optimal 75%
  # exp_learning_rate: 14 #optimal fo randomi 50%
  ^learning_rate: 
    # - 10
    # - 11
    # - 12
    - 13
    - 14
    - 15
    - 16
    # - 17

  scheduler:
    warmup_steps: 80

  checkpoint:
   load:
    type: llm-random
    path: /home/crewtool/checkpoints/def_1536_254236.pt
   save:  
    type: nano
    path: /storage_nvme_3/crewtool/nano_checkpoints/tmp # entropy
    # path: /net/scratch/hscra/plgrid/plgmstefaniak/checkpoints/tem # helios

  train_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.gpt2_tokenize_fn

  eval_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.gpt2_tokenize_fn

infrastructure:
  metric_logger:
    name: Llame_PC
    tags:
      - nano
      - pc
      - llmr_800
      - projected_compression
      # - test
      
  server: entropym
  slurm: 
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:4
    # gres: gpu:1
    # time: "0-4:00:00"
    # time: "0-8:00:00"
    time: "0-12:00:00"

  # distributed: null

apply_functions:
  - _target_: src.projected_compression.compression.init_compression
    _partial_: true
    # dimensions_importances_path: /home/crewtool/checkpoints/importances/67523/0/random_dimensions_importances.pt # random entropy llmr800
    dimensions_importances_path: /home/crewtool/checkpoints/importances/67523/0/minitron_dimensions_importances.pt # activations entropy llmr800
    target_dmodel: ${common.dmodel}
    target_dff: ${common.dff}
