# _run_: true

defaults:
  - _checkpoints@_here_: mas/hf_llama_3_1.yaml
  - _dataset@_here_: c4
  - _model@_here_: llama_3_1
  - _trainer@_here_: default


trainer:
  n_steps: 2000
  learning_rate: 0.00005
  gradient_accumulation_steps: 4


infrastructure:
  slurm:
    cpus-per-task: 16
    gres: gpu:4
    job-name: test
    mem_per_gpu: 90G
    nodes: 1
    partition: h100 # entropy
    # partition: plgrid-gpu-gh200 # helios
    time: "0-05:00:00"
    ntasks-per-node: 4

  # venv_path: $HOME/nano/.venv/bin/activate # mik entropy; mas helios
  venv_path: /dev/null
  experiment_prepare_venv_path: ${infrastructure.venv_path}

  cemetery_experiments_dir: ~/llmrandom_cemetery

  metric_logger:
    _target_: src.definitions.MetricLoggerConfig
    heavy_metrics_calculation_interval: 500
    name: test
    new_neptune_job: true
    project_name: pmtest/llm-random
    tags:
      - pc
      - nano
      - test_configs
    type: neptune

  git:
    remote_name: cemetery
    remote_url: git@github.com:llm-random/llm-random-cemetery.git

  # server: helios # helios
  server: entropy # entropy
  # server: entropy_c

  generated_configs_path: generated_configs