defaults:
  # - _cluster@_here_: helios
  - _cluster@_here_: entropy
  - _model/smollm@_here_: projected_360
  - _trainer@_here_: llama
  # - _dataset@_here_: c4
  - _dataset@_here_: fineweb
  - _checkpoints@_here_: none
  - _misc@_here_: default

common:
  sequence_length: 512
  # batch_size: 512
  batch_size: 8

trainer:
  gradient_accumulation_steps: 1
  ^n_steps: 
    - 101
    # - 4001
    # - 8001
    # - 16001
    # - 24001

  learning_rate: 16

  scheduler:
    warmup_steps: 40

  checkpoint:
   load:
    type: huggingface
    path: "HuggingFaceTB/SmolLM-360M"
  #  save:
  #   type: nano
  #   path: /storage_nvme_3/crewtool/nano_checkpoints/tmp #change

  # distributed: null

  train_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.smollm_360_tokenize_fn

  eval_dataloader:
    tokenize_fn: 
      _target_: src.core.datasets.smollm_360_tokenize_fn

infrastructure:
  metric_logger:
    name: LLMR_training
    tags:
      - nano
      - pc
      - projected_compression
      - smollm_360
      - test


  server: entropym
  slurm: 
    job-name: ${infrastructure.metric_logger.name}
    gres: gpu:1
    time: "0-4:00:00"
    # time: "0-8:00:00"
    # time: "0-12:00:00"

apply_functions:
  - _target_: src.projected_compression.compression.init_compression
    _partial_: true
    dimensions_importances_path: asd/minitron_dimensions_importances.pt # activations entropy
    # dimensions_importances_path: asd/minitron_dimensions_importances.pt # activations helios

    # # # # dimensions_importances_path: asd/random_dimensions_importances.pt # random entropy
    # # # # dimensions_importances_path: asd/random_dimensions_importances.pt # random helios
    target_dmodel: ${common.dmodel}
    target_dff: ${common.dff}