defaults:
  - _cluster@_here_: local
  - _model@_here_: tiny
  - _trainer@_here_: llama
  - _dataset@_here_: local_dummy
  - _checkpoints@_here_: none
  - _misc@_here_: default
  - _eval@_here_: default

common:
  _target_: src.definitions.Common
  dmodel: 256
  dff: 256 * 3
  datt: 256
  n_blocks: 4
  q_heads: 4
  kv_heads: 4
  vocab_size: 128256
  sequence_length: 256
  batch_size: 256
  head_norm: true
  init_scale: 0.1
  init_type: truncated_normal_fixed
  model_type: gpt

trainer:
  gradient_accumulation_steps: 1
  n_steps: 100
  ^learning_rate: [1e-3, 2e-3, 5e-3]

  checkpoint:
    save:
      type: huggingface
      path: checkpoint

infrastructure:
  metric_logger:
    name: tiny_Local
    tags:
      - nano
      - local
      - tiny

evaluator:
  limit: 1
  device: cpu