#Compare your run with: LLMRANDOM-8301
runner: "research.conditional.train.cc_train"
time: 2-00:00:00
n_gpus: 1
interactive_debug: false

# train params
params:
  name: "medium_baseline"

  model_type: gpt
  dataset_type: c4

  # base bass
  mixed_precision: false
  flash_attention: false

  # logging etc.
  logger_types : ["neptune,wandb"]
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 5000
  logging_interval_loss: 1000

  # shallower bass
  cutoff: 256
  batch_size: 256
  n_steps: 75_000
  final_lr_step: 75_000
  scheduler: cosine
  lr_warmup_steps: 750
  final_lr_fraction: 0.1

  grad_clip: 1

  #model params
  dmodel: 512
  dff: 2048
  n_blocks: 8
  n_att_heads: 8

  #hyper
  learning_rate: 0.0001

  deterministic_experiment: true
  data_seed: 21

  gradient_accumulation_steps: 2
  init_type: truncated_normal
  init_scale: 0.1
  block_modules: ["attention", "feedforward"]