interactive_debug: false
interactive_debug_session: false
md5_parent_hash: 75a39fbb8e8e4807d835dcc0c8b0cf34
params:
  activation_type: silu
  capacity_factor: 1.0
  expansion_rate: 8
  ff_mode: expert_choice
  final_lr_fraction: 0.1
  final_lr_step: 1000
  get_router_values_from: weights
  granularity: 1
  layer_norm_in_expert_choice: false
  learning_rate: 0.002
  loss_checkpoint_chungs: 4
  lr_warmup_steps: 10
  mixed_precision: true
  moe_inner_expert: ff_gated
  n_steps: 1000
  name: local_search_test_0_learning_rate_14P06TMW
  save_weights_interval: 0
  scheduler: cosine
  tags:
  - local_search
  - local_search_test_0_learning_rate_14P06TMW
  - orig_val_0.002
  - local_search_test
parent: configs/baselines/gpt/expert_choice/granularity/4/small.yaml
time: 0-0:30:00
