interactive_debug: false
interactive_debug_session: false
md5_parent_hash: 25eb0c53963eb1c7d96c91bb327c2a20
params:
  activation_type: silu
  batch_size: 512
  capacity_factor: 1.0
  cutoff: 256
  expansion_rate: 8
  ff_mode: token_choice
  final_lr_fraction: 0.06666666666666667
  final_lr_step: 8000
  get_router_values_from: weights
  granularity: 1
  layer_norm_in_expert_choice: false
  learning_rate: 0.003
  loss_checkpoint_chungs: 4
  lr_warmup_steps: 80
  mixed_precision: true
  moe_inner_expert: ff_gated
  n_steps: 8000
  name: local_search_test_1_weight_decay_EV9AFS41
  save_weights_interval: 0
  scheduler: cosine
  tags:
  - local_search
  - local_search_test_0_learning_rate_X6T3GKK0
  - orig_val_0.002
  - local_search_test
  - local_search
  - local_search_test_1_weight_decay_EV9AFS41
  - orig_val_0.15000000000000002
  - local_search_test
  weight_decay: 0.7500000000000001
parent: configs/baselines/gpt/expert_choice/granularity/4/medium.yaml
time: 0-2:00:00
