interactive_debug: false
interactive_debug_session: false
md5_parent_hash: 1706dd43c527be74a6282b0319e9c31e
params:
  batch_size: 512
  cutoff: 256
  effective_dff_x: 4
  final_lr_fraction: 0.044444
  final_lr_step: 8000
  init_scale: 0.1
  init_type: truncated_normal_fixed
  learning_rate: 0.003
  loss_checkpoint_chungs: 4
  lr_warmup_steps: 80
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  n_steps: 8000
  name: local_search_medium_truncated_fixed_0_final_lr_fraction_SNL9GRSQ
  save_weights_interval: 0
  scheduler: cosine
  tags:
  - local_search
  - local_search_medium_truncated_fixed_0_final_lr_fraction_SNL9GRSQ
  - orig_val_0.066666
  - local_search_medium_truncated_fixed
  weight_decay: 0.15
parent: configs/baselines/gpt/dense/medium.yaml
time: 0-2:00:00
