interactive_debug: false
interactive_debug_session: false
md5_parent_hash: 25eb0c53963eb1c7d96c91bb327c2a20
params:
  activation_type: silu
  batch_size: 256
  capacity_factor: 1.0
  cutoff: 512
  data_seed: 42
  expansion_rate: 8
  ff_mode: token_choice
  final_lr_fraction: 0.066666
  final_lr_step: 10240
  get_router_values_from: weights
  granularity: 1
  init_scale: 0.222
  layer_norm_in_expert_choice: false
  learning_rate: 0.0045000000000000005
  load_balancing_loss_weight: 0.01
  loss_checkpoint_chungs: 4
  lr_warmup_steps: 102
  mixed_precision: true
  moe_inner_expert: ff_gated
  n_steps: 10240
  name: local_search_relative_medium_0_weight_decay_S6C790IG
  print_parameter_names: true
  save_weights_interval: 0
  scheduler: cosine
  tags:
  - relative
  - compute_opt
  - local_search_medium_new
  - baseline
  - local_search
  - local_search_relative_medium_0_learning_rate_ZTJR5BV9
  - orig_val_0.003
  - local_search_relative_medium
  - local_search
  - local_search_relative_medium_0_weight_decay_S6C790IG
  - orig_val_0.15
  - local_search_relative_medium
  weight_decay: 0.22499999999999998
  zloss_weight: 0.001
parent: configs/baselines/gpt/expert_choice/granularity/4/medium.yaml
time: 0-10:00:00
