interactive_debug: false
interactive_debug_session: false
md5_parent_hash: 25eb0c53963eb1c7d96c91bb327c2a20
params:
  activation_type: silu
  batch_size: 512
  capacity_factor: 1.0
  cutoff: 256
  expansion_rate: 8
  ff_mode: token_choice
  final_lr_fraction: 0.066666
  final_lr_step: 4000
  get_router_values_from: weights
  granularity: 1
  init_scale: 0.333
  layer_norm_in_expert_choice: false
  learning_rate: 0.003
  loss_checkpoint_chungs: 4
  lr_warmup_steps: 40
  mixed_precision: true
  moe_inner_expert: ff_gated
  n_steps: 4000
  name: local_search_relative_moe_short_2_relative_lr_expert_inner_function_ANQRNCCU
  print_parameter_names: true
  relative_init_scale:
    embedding_layer: 0.2
    expert_inner_function: 1.0
    gating: 0.2
    head: 1.0
  relative_lr:
    embedding_layer: 3.333333333333333
    expert_inner_function: 0.19999999999999998
    gating: 0.9990000000000001
    head: 0.444
  relative_scheduler_fraction:
    embedding_layer: 0.6666666666666666
    expert_inner_function: 1.5
    gating: 1.0
    head: 1.0
  save_weights_interval: 0
  scheduler: cosine
  tags:
  - local_search
  - local_search_relative_moe_short_0_relative_init_scale_gating_IYJ5DIHC
  - orig_val_1.0
  - local_search_relative_moe_short
  - local_search
  - local_search_relative_moe_short_2_relative_lr_expert_inner_function_ANQRNCCU
  - orig_val_0.3
  - local_search_relative_moe_short
  weight_decay: 0.15
parent: configs/baselines/gpt/expert_choice/granularity/4/medium.yaml
time: 0-2:00:00
