interactive_debug: false
interactive_debug_session: false
md5_parent_hash: 1706dd43c527be74a6282b0319e9c31e
params:
  batch_size: 512
  cutoff: 256
  effective_dff_x: 4
  final_lr_fraction: 0.04444
  final_lr_step: 8000
  init_scale: 0.5
  init_type: truncated_normal
  learning_rate: 0.0045000000000000005
  loss_checkpoint_chungs: 4
  lr_warmup_steps: 80
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  n_steps: 8000
  name: local_search_medium_relative_lr_0_learning_rate_LGVFQBBQ
  relative_init_scale:
    embedding_layer: 1
    head: 1
  relative_lr:
    embedding_layer: 1.5
    head: 1
  save_weights_interval: 0
  scheduler: cosine
  tags:
  - local_search
  - local_search_medium_relative_lr_0_relative_lr_head_JERTMXBZ
  - orig_val_1
  - local_search_medium_relative_lr
  - local_search
  - local_search_medium_relative_lr_0_learning_rate_LGVFQBBQ
  - orig_val_0.003
  - local_search_medium_relative_lr
  weight_decay: 0.225
parent: configs/baselines/gpt/dense/medium.yaml
time: 0-2:00:00
