parent: configs/mole/common_base.yaml
md5_parent_hash: c4ecc588268f690de51810a2b20f66a4
time: 0-19:50:00
n_gpus: 2
# n_gpus: 4 # athena

# cpus_per_gpu: 20 # writer
cpus_per_gpu: 25 # entropy
# cpus_per_gpu: 16 # athena

params:
  name: "MoLE"
  tags: ["mole", "base", "lr_+"]

  ^biased_balancing_loss_weight: [0]
  ^load_balancing_loss_weight: [0.015625]
  ^learning_rate: [0.000125]

  num_workers: 14 # entropy
  # num_workers: 16 # athena, writer