parent: configs/mole/common.yaml
time: 1-23:50:00
n_gpus: 2
# n_gpus: 4 # athena

# cpus_per_gpu: 20 # writer
cpus_per_gpu: 25 # entropy
# cpus_per_gpu: 16 # athena
md5_parent_hash: 934810b5bf85d2b00bc41bf6e9dc9e5f

params:
  dmodel: 768
  dff: 3072
  n_blocks: 12
  n_att_heads: 12
  n_steps: 43_200
  final_lr_step: 43_200

  name: "MoLE"
  tags: ["mole", "base", "first_run"]

  ^biased_balancing_loss_weight: [0]
  ^load_balancing_loss_weight: [0.015625]
  ^learning_rate: [0.00025, 0.0005, 0.00075]
  # ^learning_rate: [0.0005]

  num_workers: 14 # entropy
  # num_workers: 16 # athena, writer