parent: configs/mole/common.yaml
time: 0-20:50:00
n_gpus: 4
# n_gpus: 4 # athena
# cpus_per_gpu: 20 # writer
cpus_per_gpu: 30 # entropy
# cpus_per_gpu: 16 # athena
md5_parent_hash: 934810b5bf85d2b00bc41bf6e9dc9e5f

params:
  dmodel: 768
  dff: 3072
  n_blocks: 12
  n_att_heads: 12
  n_steps: 43_200
  final_lr_step: 43_200

  name: "MoLE"
  tags: ["mole", "base", "first_run"]

  ^biased_balancing_loss_weight: [0]
  ^load_balancing_loss_weight: [0.015625]
  pos_grouped: "{'NOUN':[0,9],'PUNCT':[9,14],'VERB':[14,19],'ADP':[19,24],'PROPN':[24,28],'DET':[28,32],'ADJ':[32,35],'PRON':[35,38],'AUX':[38,40],'ADV':[40,42],'CCONJ':[42,44],'PART':[44,45],'NUM':[45,46],'EOT':[46,47],'SPACE':[46,47],'SYM':[46,47],'X':[46,47],'INTJ':[46,47],'SCONJ':[47,48],}"
  expansion_rate: 48
  # learning_rate: 0.0005
  ^learning_rate: [0.00025, 0.00075]
  # ^learning_rate: [0.0005]

  num_workers: 14 # entropy
  # num_workers: 16 # athena, writer