parent: configs/mole/common.yaml
time: 0-00:20:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: f46521584cb698bb67ed75c907d2eb38

params:
  name: "MoLE"
  tags: ["mole", "ms", "implementation", "dev_quick", "default"]
  