parent: configs/mole/common.yaml
time: 0-00:10:00
n_gpus: 1
cpus_per_gpu: 4
md5_parent_hash: ee4b9df15668b451c5ed48a95dea6404

params:
  name: "MoLE"
  tags: ["mole", "ms", "implementation", "dev_quick", "default"]
  