parent: configs/mole/common.yaml
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: aa9e102b30305b3ea32dd6bc26470017

params:
  name: "MoLE"
  tags: ["mole", "ms", "dev", "num_workers: 8"]
  num_workers: 8
  