parent: configs/mole/common.yaml
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: 87726d7139de07b26f87399f8bc95774

params:
  name: "MoLE"
  tags: ["mole", "ms", "dev", "num_workers: 8"]
  num_workers: 8
  