parent: configs/mole/conditional.yaml
time: 0-01:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: 7f4dfaa9ab7da73fb3b2071e4ff1f8da

params:
  name: "MoLE"
  tags: ["mole", "ms", "conditional_dev", "num_workers: 16"]
  num_workers: 16
  