parent: configs/mole/common.yaml
time: 0-03:00:00
n_gpus: 2
cpus_per_gpu: 16
md5_parent_hash: 2bbaa5654dd34fb554045eb46b465f99

params:
  name: "MoLE"
  tags: ["mole", "ms", "test_pos_router"]
  ^load_balancing_loss_weight: [0.01, 0.00]
  ^biased_balancing_loss_weight: [0.000001, 0.000000001, 0.000000000000001]
  num_workers: 16
  logging_interval_loss: 100
  