parent: configs/mole/common.yaml
time: 0-05:00:00
n_gpus: 2
cpus_per_gpu: 16
md5_parent_hash: 934810b5bf85d2b00bc41bf6e9dc9e5f

params:
  name: "MoLE_grid_nl"
  tags: ["mole", "new_loss_1", "sparse_grid", "BCEWithLogitsLoss", "reproduce"]
  ^biased_balancing_loss_weight: [0.00390625, 0.0078125, 0.00195313, 0.015625]
  ^load_balancing_loss_weight: [0.015625]

  num_workers: 16
