parent: configs/mole/common.yaml
time: 0-10:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: fd9382e24ed41a4a03b5a1054cab1401

params:
  name: "MoLE_calc"
  tags: ["mole", "calc", "tokens_distribution"]
  