parent: configs/mole/common.yaml
time: 0-20:50:00
n_gpus: 1
# n_gpus: 2 # athena
cpus_per_gpu: 26 # writer
# cpus_per_gpu: 32 # entropy
# cpus_per_gpu: 16 # athena
md5_parent_hash: beb25eb5bde5162901852770bbb83dee

params:
  name: "MoLE"
  tags: ["mole", "softmax", "lr_grid_2"]
  ^biased_balancing_loss_weight: [0, 0.125]
  ^load_balancing_loss_weight: [0.015625]
  pos_grouped: "{'NOUN':[0,9],'PUNCT':[9,14],'VERB':[14,19],'ADP':[19,24],'PROPN':[24,28],'DET':[28,32],'ADJ':[32,35],'PRON':[35,38],'AUX':[38,40],'ADV':[40,42],'CCONJ':[42,44],'PART':[44,45],'NUM':[45,46],'EOT':[46,47],'SPACE':[46,47],'SYM':[46,47],'X':[46,47],'INTJ':[46,47],'SCONJ':[47,48],}"
  expansion_rate: 48
  num_workers: 24 # writer
  ^learning_rate: [0.001, 0.0015, 0.002, 0.0025, 0.003]

  # num_workers: 15 # entropy
  # num_workers: 16 # athena
  