parent: configs/mole/common.yaml
time: 0-05:50:00

n_gpus: 1 # writer entropy
# n_gpus: 2 # athena

cpus_per_gpu: 26 # writer
# cpus_per_gpu: 32 # entropy
# cpus_per_gpu: 16 # athena

md5_parent_hash: ab7eee873b6b1f23d8fa4692d3b9a619

params:
  name: "MoLE"
  tags: ["mole", "softmax", "lr_grid_2"]
  # ^biased_balancing_loss_weight: [0, 0.125]
  ^biased_balancing_loss_weight: [0.0]
  ^load_balancing_loss_weight: [0.015625]
  # learning_rate: 0.002
  ^learning_rate: [0.001, 0.0015, 0.002, 0.0025, 0.003]

  num_workers: 24 # writer
  # num_workers: 15 # entropy
  # num_workers: 16 # athena
  