parent: configs/mole/common.yaml
time: 0-10:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: 87726d7139de07b26f87399f8bc95774

params:
  name: "MoLE_calc"
  tags: ["mole", "calc", "tokens_distribution"]
  