parent: configs/mole/common.yaml
time: 0-10:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: 928964a491a1588ab60911199e2db4eb

params:
  name: "MoLE_calc"
  tags: ["mole", "calc", "tokens_distribution"]
  