parent: configs/mole/common.yaml
time: 0-10:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: aa9e102b30305b3ea32dd6bc26470017

params:
  name: "MoLE_calc"
  tags: ["mole", "calc", "tokens_distribution"]
  