parent: configs/mole/common.yaml
time: 0-05:00:00
n_gpus: 2
cpus_per_gpu: 16
md5_parent_hash: f46521584cb698bb67ed75c907d2eb38

params:
  name: "MoLE"
  tags: ["mole", "ms", "16_cpus", "16_num_workers"]
  biased_balancing_loss_weight: 0.01
  load_balancing_loss_weight: 0.0
  num_workers: 16
  