parent: configs/mole/common.yaml
time: 0-03:30:00
n_gpus: 2
cpus_per_gpu: 16
md5_parent_hash: 2bbaa5654dd34fb554045eb46b465f99

params:
  name: "MoLE"
  tags: ["mole", "default", "test_reproducibility"]
  ^biased_balancing_loss_weight: [0.01, 0.00]
  ^load_balancing_loss_weight: [0.01]
  