parent: configs/mole/common.yaml
time: 0-10:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: b9ab7d3c624f9f12fdefb10dfee56edb

params:
  name: "MoLE"
  tags: ["mole", "ms", "test_run"]
  ^biased_balancing_loss_weight: [0.01, 0.00]
  ^load_balancing_loss_weight: [0.01, 0.01, 0.01]
  num_workers: 16
  logging_interval_loss: 100
  