parent: configs/mole/common.yaml
time: 0-10:00:00
n_gpus: 1
cpus_per_gpu: 16
md5_parent_hash: 934810b5bf85d2b00bc41bf6e9dc9e5f

params:
  name: "MoLE_calc"
  tags: ["mole", "calc", "tokens_distribution"]
  