parent: configs/mole/common.yaml
time: 0-05:00:00
n_gpus: 2
cpus_per_gpu: 16
md5_parent_hash: 87726d7139de07b26f87399f8bc95774

params:
  name: "MoLE_grid_nl"
  tags: ["mole", "hash", "new_loss_2", "sparse_grid", "sigmoid", "test_no_pos_grouped"]
  ^biased_balancing_loss_weight: [0.25]
  ^load_balancing_loss_weight: [0.015625]
  biased: hash_token
  pos_grouped: Null
  expansion_rate: 48
  
  num_workers: 16