parent: configs/mole/common.yaml
md5_parent_hash: c7e284c7ce24a161e67f2011d5b49190
time: 0-05:50:00
n_gpus: 2
cpus_per_gpu: 16 # athena, writer
# cpus_per_gpu: 26 # writera
# cpus_per_gpu: 20 # entropy

params:
  name: "MoLE_su"
  tags: ["mole", "G2", "medium", "tuned_speedup", "rep_var"]
  # ^biased_balancing_loss_weight: [0.0]
  ^biased_balancing_loss_weight: [0.015625]
  ^load_balancing_loss_weight: [0.03125]
  n_steps: 12_800
  checkpoint_manager: True
  scheduler_trapezoidal_slides: "[{'n_steps':10200},{'n_steps':10900},{'n_steps':11500},{'n_steps':12200}]"
  ^data_seed: [28, 29, 30]

  # num_workers: 24 # writer
  num_workers: 16 # athena, writer
  # num_workers: 14 # entropy