parent: configs/mole/common.yaml
time: 0-03:30:00
n_gpus: 2
cpus_per_gpu: 16
md5_parent_hash: 88b42d6df8736803531efbdaa0bb401e

params:
  name: "MoLE"
  tags: ["mole", "default"]
  ^biased_balancing_loss_weight: [0.01, 0.00]
  ^load_balancing_loss_weight: [0.01]
  