parent: configs/mole/common.yaml
time: 0-05:00:00
n_gpus: 1
cpus_per_gpu: 32
md5_parent_hash: f46521584cb698bb67ed75c907d2eb38

params:
  name: "MoLE"
  tags: ["mole", "ms", "32_cpus", "32_num_workers"]
  biased_balancing_loss_weight: 0.01
  load_balancing_loss_weight: 0.0
  num_workers: 32
  