parent: research/conditional/train/configs/baselines/gpt/small.yaml
md5_parent_hash: cbdf4e5992f41713488c25c819086e51
time: "0-1:00:00"
runner: "research.blanks.train"
# interactive_debug: true

params:
  name: blanx-eval-testing
  learning_rate: 1e-3
  n_steps: 100000

  tokenizer: gpt
  # blanx args
  ^n_blanks: [1]
  ^blanks_residual: [true]
  ^blanks_add_embedding: [false]
  blanks_learnable_weights: true
  ^blank_initial_weight: [0.00001]
  ^blanks_use_straight_through: [true]
  init_type: kaiming_uniform
  init_scale: 1.0

  # blank_initial_weight: 10.0
  # blanks_use_straight_through: true
  # LOCAL:
  # dmodel: 8
  # dff: 8
  # n_blocks: 1
  # n_att_heads: 8

  # batch_size: 32
  # use_dummy_dataset: true
  # num_workers: 2
