# parent: research/blanks/configs/medium.yaml
# md5_parent_hash: 9090e17e318c69eab30160e17f0af756
time: "0-10:00:00"
runner: "research.blanks.train"
# cuda_visible: "4"
n_gpus: 1

# interactive_debug: false

params:
  init_type: kaiming_uniform
  init_scale: 1.0
  mixed_precision: true
  # logging etc.
  use_neptune: true
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 5000
  logging_interval_loss: 1000
  save_weights_path: "model_ckpt"
  save_weights_interval: 200_000
  # shallower bass
  cutoff: 256
  final_lr_step: 100_000
  scheduler: cosine
  lr_warmup_steps: 2500
  final_lr_fraction: 0.1
  grad_clip: 0.5

  dmodel: 512
  dff: 2048
  n_blocks: 8
  n_att_heads: 8
  name: sj-blanx
  learning_rate: 1e-3
  n_steps: 100_000
  batch_size: 192
  tags: ["sj-blanx"]

  tokenizer: gpt
  # blanx args
  blanks_extend_sequence_by_n_blanks: true

  ^n_blanks: [1]
  ^blanks_residual: [true]
  ^blanks_learnable_weights: [true]
  ^blanks_use_multiple_embeddings: [true]
  ^blanks_use_straight_through: [false]
  ^blank_initial_weight: [1.0]
  ^blanks_use_only_last_blank_loss: [false]
  ^blanks_use_separate_head: [true]

  # ^blanks_add_embedding: [false, true]
  # blanks_learnable_weights: true
  # ^blanks_use_straight_through: [true, false]
  # ^blanks_use_multiple_embeddings: [true, false]
  # ^blanks_use_only_last_blank_loss: [false, true]
  # blanks_use_separate_head: true
  # ^blanks_use_separate_head: [true]

  blanks_use_custom_positional_embedding: true
  blanks_use_custom_attention: true

  # blank_initial_weight: 10.0
  # blanks_use_straight_through: true
  # LOCAL:
  dataset_type: c4
  # batch_size: 2
  # dataset_type: wikibook
  # use_dummy_dataset: true
  # num_workers: 0