runner: "research.attention_moe.train.train"
time: 0-16:00:00
n_gpus: 4
interactive_debug: false
backends_module: research.attention_moe.backends

# train params
params:
  name: "debug_diff"

  # base bass
  mixed_precision: true
  flash_attention: true

  # logging etc.
  logger_types: "neptune"
  project_name: "pmtest/llm-random"
  logging_interval_heavy: 1000
  logging_interval_light: 500
  logging_interval_loss: 1000
  save_weights_path: "model_ckpt"
  save_weights_interval: -1
  tags: ["mqa_diff"]


  cutoff: 1024
  batch_size: 128
  n_steps: 60_000
  final_lr_step: 60_000
  scheduler: cosine
  lr_warmup_steps: 600
  final_lr_fraction: 0.1
  gradient_accumulation_steps: 1

  grad_clip: 1.0
  model_type: gpt
  dataset_type: c4
  # capacity_factor: 1.25
  weight_decay: 0.01
  # topk: 1
  
  # model
  use_rope: true
  ^attention_mode: [
    # "diff_vanilla_fast1",
    "diff_theirs_fast1"
  ]
  ^dmodel: [1024]
  dff: 4096
  n_blocks: 16
  n_att_heads: 16
  ^learning_rate: [1e-4]
  data_seed: 42
  init_type: truncated_normal
  init_scale: 0.1
  mixed_precision_dtype: bfloat16
  ^diff_transformer_lowrank_dim: [64, 0]
  diff_transformer_roll_negative_heads: true
  ^n_kv_heads: [2]
  # ^load_balancing_loss_weight: [0.01]

  # fsdp
  fsdp_enabled: true
  fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
  fsdp_selective_precision_modules: "AttentionMechanism,RoPE"
  torch_compile: false
  