parent: configs/experiments/constrained_scaling_laws/30M/model.yaml
md5_parent_hash: f561415b71eaca175252470778d9cf71
time: "01:12:00"
n_gpus: 1
cpus_per_gpu: 16
params:
  name: "checkpoint_manager"
  tags: ["checkpoint_manager", "test"]
  expansion_rate: 4
  n_steps: 2600
  batch_size: 100
  cutoff: 256
  loss_checkpoint_chungs: 0
  save_weights_path: "./model_saves"
  checkpoint_manager: True
  scheduler_trapezoidal_slides: "[{'n_steps':100},{'n_steps':200}]"
  batch_size_rampup_transition_points: [0.001, 0.002]
  batch_size_rampup_sizes: [25, 50]

  scheduler: trapezoidal
  fsdp_enabled: True
  # save_weights_interval: 100

