time: "01:12:00"
n_gpus: 2
cpus_per_gpu: 16

params:
  dmodel: 256
  n_blocks: 4
  n_att_heads: 8
  model_type: gpt

  expansion_rate: 4
  effective_dff_x: 4
  granularity: 1

  dataset_type: c4
  batch_size: 100
  cutoff: 256

  n_steps: 2600

  name: "checkpoint_manager_example"
  tags: ["checkpoint_manager", "feature_presentation", "test"]
  save_weights_path: "/local_storage_2/llm-random/model_checkpoints/tmp"
  checkpoint_manager: True
  lr_trapezoidal_decay_fraction_unit: steps
  scheduler_trapezoidal_slides: "[{'n_steps':1000},{'n_steps':2000}]"
  scheduler: trapezoidal
  fsdp_enabled: True
  fsdp_modules_to_wrap: EmbeddingLayer,PredictionHead,TransformerBlock
  data_seed: 27

  logger_types: "neptune"
  logging_interval_heavy: 500
  logging_interval_loss: 100
  learning_rate: 0.002
  init_type: kaiming_uniform
  init_scal: 0.1
  lr_warmup_steps: 260
  ff_mode: token_choice
  