parent: configs/experiments/constrained_scaling_laws/25M/model.yaml
md5_parent_hash: 3067b2550c57a4b87c0c6a1287e6d902
time: "48:00:00"
n_gpus: 2
params:
  name: scheduler_trapezoidal
  tags: ["mstest", "25M", "trapezoidal_scheduler", "checkpoint_manager", "grid"]
  expansion_rate: 8
  learning_rate: 0.001
  n_steps: 13000
  scheduler: trapezoidal
  lr_warmup_percent: 0.01
  lr_trapezoidal_decay_fraction: 0.2
  data_seed: 44
  checkpoint_manager: True
  scheduler_trapezoidal_slides: "[{'n_steps':2600},{'n_steps':5200}]"
  scheduler: trapezoidal
  fsdp_enabled: True
  logger_types: Null
  loss_checkpoint_chungs: 0
  gradient_accumulation_steps: 4

  # name: scheduler_trapezoidal
  # tags: ["mstest", "25M", "trapezoidal_scheduler", "test"]
  # expansion_rate: 8
  # n_steps: 10
  # lr_warmup_percent: 0.1
  # ^lr_trapezoidal_decay_fraction: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  # # lr_trapezoidal_decay_fraction: 0.1
  # scheduler: trapezoidal
  # fsdp_enabled: false


