scalings:
  - name: "dense"
    tags:
      - "zubr_dense_grid"
    tags_negative:
      - "short_small"
      - "short_dense"
    fixed:
      expansion_rate: 1
      granularity: 0
    power_laws:
      - - "n_params"
      - - "n_steps"
    cmap: copper
    weight_decay: 0.00001
    huber_delta: 0.1
    opt_log_loss: true
  - name: "Granular Scaling"
    tags:
      - "fixed_grid_wd"
      - "big_models"
      # - "long"
    tags_negative:
      - "gran_grid_failed"
      - "mini_8"
      - "short_small"
      - "lr_steps_bug"
      - "small_gran"
      # - "longest"
      - "mini_short"
      - "grid_shortest"
      - "short_small_ext"
      - "short_small_ext_ext"
    fixed:
      expansion_rate: 64
    power_laws:
      - - "n_params"
        - "granularity"
      - - "n_steps"
    exp_inter: false
    poly_inter: true
    cmap: rainbow
    resolve_interactive: true
    use_active_params: true
    weight_decay: 0.00005
    huber_delta: 0.1
    opt_log_loss: false
plot_dims:
  - - "predicted_loss"
    - "granularity"
  - - "predicted_loss"
    - "n_steps"
#  - - "predicted_loss"
#    - "n_params"
  - - "flops"
    - "n_params"
    - "n_steps"
#  - - "flops"
#    - "n_steps"
#  - - "flops"
#    - "n_params"
#  - - "granularity"
#  - - "n_steps"
#  - - "n_params"
extrapolate_factor: 3.0
use_scipy: true
load_model: false
scaling_bias: 0.472
show_model_sizes:
#  10M: 10e6
  100M: 100e6
  500M: 500e6
  1B: 1e9
  3B: 3e9
  7B: 7e9
  70B: 70e9
  500B: 500e9
  1T: 1e12
plot_points: 100
no_title: false
project_name: "pmtest/llm-random"