parent: research/conditional/train/configs/baselines/gpt/mini.yaml
md5_parent_hash: 019212718f2ace8645ddca8f28f6eaee
n_gpus: 1
cuda_visible: "1"

params:
  dmodel: 284
  # technical/common params
  mixed_precision: true
  ff_mode: expert_choice
  softmax_over: experts
  group_granular_moe_by_batch: true
  use_full_einsum: true
  granular_moe_one_hot_impl: true
  ^flash_attention: [false]
  logging_interval_heavy: 1_000_000
  logging_interval_light: 300_000
  decoding_interval: 0

  # init
  init_type: truncated_normal
  init_scale: 0.1

  # params of expert choice
  total_experts_width: 32768
  effective_dff: 1024
  ^n_experts: [32]

  # ------ FILL IN BELOW ------
  n_steps: 150_000
  scheduler: cosine
  learning_rate: 1e-4
  lr_warmup_steps: 175_000
  final_lr_step: 150_000
  batch_size: 128
  cutoff: 256
  weight_decay: 0.01
