parent: configs/baselines/gpt/dense/base.yaml
md5_parent_hash: 763f39978a58f704200275285162594c
time: "2-00:00:00"
runner: "research.token_reduction.utils.runner"
n_gpus: 1

params:
  name: "base_merging_scheduled_1.3"
  tags: ["base", "merging", "scheduled", "1.3", "token_reduction"]
  wandb_project: "token_reduction"

  reduction_layer_type: "merging"
  ^cutoff: [1024]
  batch_size: 256
  learning_rate: 1e-3
  gradient_accumulation_steps: 4
  ^tr_schedule: 
    - "90_cos_1.3-1;10_const_1"
    - "100_cos_1.3-1"
    - "90_lin_1.3-1;10_const_1"
    - "100_lin_1.3-1"
    - "45_const_1.3;45_lin_1.3-1;10_const_1"
    - "45_const_1.3;45_cos_1.3-1;10_const_1"
    - "100_const_1.3"


  n_steps: 8_000
  final_lr_step: 8_000
  lr_warmup_steps: 80
  final_lr_fraction: 0.1


  # precision / distributed
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  flash_attention: true

  # common
  scheduler: cosine
  init_type: truncated_normal
  init_scale: 0.1
  dataset_type: c4
  weight_decay: 0.1
  grad_clip: 0.1
  logger_types: "neptune,wandb"

  # intervals
  decoding_interval: 0
  logging_interval_heavy: 1000
  logging_interval_light: 100
  save_weights_interval: 0
  eval_interval: 100