parent: configs/baselines/gpt/dense/medium.yaml
md5_parent_hash: 1706dd43c527be74a6282b0319e9c31e
time: "2-00:00:00"
runner: "research.token_reduction.runner"

params:
  name: "medium"
  logger_types: "neptune,wandb"
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  flash_attention: true
  grad_clip: 1.0
  tags: ["baseline", "medium"]


  n_steps: 75_000
  learning_rate: 1e-4
  decoding_interval: 0
  logging_interval_heavy: 1000
  init_type: truncated_normal
  init_scale: 0.1
  save_weights_interval: 0
  batch_size: 64
  dataset_type: c4

  eval_interval: 100  
  
  ^cutoff: [2252, 2464, 3072, 4096]
  reduced_number_of_tokens: 2048
  # cutoff: 1024



  # cutoff: 32
  # reduced_number_of_tokens: 24
  # batch_size: 8
  # dmodel: 32
  # dff: 128
  # n_blocks: 2
  # n_att_heads: 2
  # use_dummy_dataset: true
