parent: configs/baselines/gpt/dense/large.yaml
md5_parent_hash: 66aa609ebcff1d88f0bb900b0a0966fb
time: "3-00:00:00"
cuda_visible: "2"
runner: "research.token_reduction.utils.runner"
n_gpus: 1

params:
  # name: "base_merging_scheduled_1_1"
  # tags: ["base", "merging", "scheduled", "1.1", "token_reduction"]
  name: "large_vanilla"
  tags: ["large", "vanilla", "token_reduction"]
  wandb_project: "token_reduction"

  # reduction_layer_type: "merging"
  ^cutoff: [2048] 
  batch_size: 128
  learning_rate: 1e-4
  gradient_accumulation_steps: 8
  # ^tr_schedule: 
  #   - "90_cos_1.1-1;10_const_1"
  #   - "100_cos_1.1-1"
    # - "90_lin_1.1-1;10_const_1"
    # - "100_lin_1.1-1"
    # - "45_const_1.1;45_lin_1.1-1;10_const_1"
    # - "45_const_1.1;45_cos_1.1-1;10_const_1"
    # - "100_const_1.1"


  n_steps: 16_000
  final_lr_step: 16_000
  lr_warmup_steps: 160
  final_lr_fraction: 0.1


  # precision / distributed
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  flash_attention: true

  # common
  scheduler: cosine
  init_type: truncated_normal
  init_scale: 0.1
  dataset_type: c4
  weight_decay: 0.1
  grad_clip: 0.1
  logger_types: "neptune,wandb"

  # intervals
  decoding_interval: 0
  logging_interval_heavy: 1000
  logging_interval_light: 100
  save_weights_interval: 0
  eval_interval: 100

  loss_checkpoint_chungs: 4

  #fsdp
  fsdp_enabled: true
  fsdp_modules_to_wrap: "TransformerBlock,TokenReductionEmbedding,PredictionHead"
  fsdp_selective_precision_modules: "AttentionMechanism"
